shell/deploy-to-dev.sh, shell/devconfig.sh
=> fix: Use correct path for devconfig override and app josnnet

root/Makefile
**What this PR does / why we need it**: As the title says, it does!
**JIRA ID**: DT-0
=> feat(Makefile): allow overriding LDFLAGS

shell/opslevel/upload.sh
**What this PR does / why we need it**: Empty shell to run all OpsLevel related uploads.
**JIRA ID**: [DT-509]
**Notes for your reviewer**: This is an empty shell to let us update bootstrap templates to invoke it. Actual upload functionality comes in separate PRs.
[DT-509]: https://outreach-io.atlassian.net/browse/DT-509
=> feat(bootstrap): intro opslevel shell

e2e/e2e.go
* Conditionally skips e2e tests if no `or_e2e` build tags are found.
=> feat: skip e2e based off build tags

root/Makefile
* Adds benchmarker make targets to bootstrapped repositories
**JIRA ID**: DTSS-488
=> feat: benchmarker make targets [DTSS-488]

root/Makefile
* bootstrap ci test failed and pointed this out
* sorry for letting everyone down
=> fix: formatting on benchmarker makefile targets

e2e/e2e.go
**What this PR does / why we need it**:  `make e2e` is skipping all the e2e tests without this.
**JIRA ID**: DT-00
It looks like `ast.Inspect` silently ignores build constraints (and probably all directives too).   I fixed it to use `build.Import`. 
Note that build.Import can actually process a whole directory in one shot and we should probably use that but wanted to make a smaller change and unblock myself for now.
=> fix: use go/build to check build tags for or_e2e

shell/golangci-lint.sh, versions.yaml
* golangci-lint is getting OOM-killed in CI. This and a corresponding bootstrap PR that disables misspell hopefully will resolve things.
=> feat: update golangci-lint version

shell/golangci-lint.sh
* Trade less memory use for more CPU use when linting.
=> fix: set gogc for linting

shell/protoc.sh
This PR updates devbase to use the latest grpc tooling. The goal here is to allow generation of grpc client libs that use grpc-js instead of the the now deprecated 'grpc' lib.
**JIRA ID**: [DT-355]
=> feat(protoc):Updating to a more recent version of grpc-js

shell/test.sh, versions.yaml
**What this PR does / why we need it**: Title says, it does. 
=> feat: support junit output for unit/e2e tests

shell/hjson-json.sh
**What this PR does / why we need it**: Title says, it does. Not sure why this didn't work before 
=> fix(hjson): support newer gobin

root/Makefile, shell/test.sh, shell/validate.sh
=> feat: account for oss variable in makefile

shell/validate.sh
=> fix: bad conditional

e2e/e2e.go
**What this PR does / why we need it**: This PR fixes our dependency resolution to properly resolve initial dependencies. Before we'd mark them as already downloaded, which lead us to skip actually resolving their dependencies. This fixes that logic to ensure we resolve their dependencies.
**Notes for your reviewer**: [**CONTEXT**](https://outreach-hq.slack.com/archives/CN9MU7GLW/p1629322358474200)
=> fix: properly resolve initial dependencies

root/Makefile
**What this PR does / why we need it**: This PR brings support for different orgs and documents the current options
=> feat: support different orgs

shell/test.sh
**What this PR does / why we need it**: This fixes `OSS` trying to be executed resulting in a "command not found" error.
**Notes for your reviewer**: @george-e-shaw-iv
=> fix(test): don't try to exec OSS envvar

e2e/e2e.go
**What this PR does / why we need it**: This PR fixes the e2e dependency resolution logic to prevent a infinite dependency resolution loop on cyclical dependencies. 
**Notes for your reviewer**: [**CONTEXT**](https://outreach-hq.slack.com/archives/CN9MU7GLW/p1632255774102000)
=> fix(e2e): prevent inf dependency resolution on cyclical deps

versions.yaml
=> fix: update lintroller

Makefile
**What this PR does / why we need it**: Title says... it does. 
=> fix: orb.yaml -> orb.yml

shell/validate.sh
Remove code owner check for now due to rate github rate limiting impact.
=> fix: comment out code owners due to ci rate limits

versions.yaml
Updates `clerkgenproto` version to [1.15.0](https://github.com/getoutreach/clerkgen/releases/tag/v1.15.0)
=> fix: Update clerkgenproto version

orbs/shared/commands/save_go_cache.yml, orbs/shared/commands/with_go_cache.yml, shell/ci/release/dryrun.sh
**What this PR does / why we need it**: Title says, it does. Now we fake squash in the dryrun 
=> fix(ci/release): accidental regression in dryrun, emulate squash

shell/ci/release/dryrun.sh
**What this PR does / why we need it**: This fixes an issue where the dryrun step could fail if the base branch was behind the head branch. 
=> fix(release/dryrun): setup git config earlier

orbs/shared/commands/setup_environment.yml
* add the ability to set golang version in machines
* https://outreach-hq.slack.com/archives/CN9MU7GLW/p1637104259376700
=> feat: golang version in ci machines

orbs/shared/commands/setup_environment.yml
* permission denied errors since i was executing commands that affected directories outside of the home directory
=> fix: ci machine perms

.circleci/config.yml, shell/validate.sh
**What this PR does / why we need it**: ASDF stuff is taking a bit, so we fix the `run_node_command` bug here. 
=> fix(validate): dont use run_node_command

versions.yaml
Updates clerkgenproto's version [Release](https://github.com/getoutreach/clerkgen/releases/tag/v1.16.2)
**JIRA ID**: DP-3004
=> fix: [DP-3004] Update clerkgenproto

shell/gobin.sh
**What this PR does / why we need it**: Title says, it does. 
=> fix: update gobin

orbs/shared/commands/setup_environment.yml
=> feat: checkout submodules in ci

shell/ci/testing/coveralls.sh
=> fix: prepend v to goveralls version

orbs/shared/commands/setup_environment.yml, shell/ci/auth/github_packages.sh, shell/ci/env/asdf.sh, shell/lib/asdf.sh
See comment in source code for why
[XX-XX]
=> feat(github_packages): allow overriding token used just for packages

versions.yaml
=> fix(lintroller): update to v1.10.1

shell/ci/testing/wait-for-infra.sh, shell/lib/bootstrap.sh
Fixes some small typos in the `wait-for-infra` script to make it actually function now.
[DTSS-0]
=> fix(wait-for-infra): actually wait

versions.yaml
[VI-4793]
[VI-4793]: https://outreach-io.atlassian.net/browse/VI-4793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: pickup lintroller fix for cgo support

shell/validate.sh
Fixes an issue where linting could pass locally but fail in CI. [**CONTEXT**](https://outreach-hq.slack.com/archives/CN9MU7GLW/p1641428344001000)
[XX-XX]
=> fix(validate/golangci-lint): validate all build tags always

shell/test.sh, shell/validate.sh
Title says, it does.'
Also updated to skip lintroller if no go files are found.
[DTSS-1138]
[DTSS-1138]: https://outreach-io.atlassian.net/browse/DTSS-1138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(test): skip go.sum check when it doesnt exist (DTSS-1138)

shell/ci/testing/wait-for-infra.sh
Removing support for Temporal as its no longer supported
[DTSS-1163]
[DTSS-1163]: https://outreach-io.atlassian.net/browse/DTSS-1163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove temporal from the list as its being removed

shell/gobin.sh, shell/languages/nodejs.sh, shell/lib/shell.sh, shell/shellcheck.sh
Title says it all.
[DTSS-1186]
[DTSS-1186]: https://outreach-io.atlassian.net/browse/DTSS-1186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: retry common failure points

shell/deploy-to-dev.sh
Title says, it does. This enables us to pass version in the devenv.
[DTSS-478]
[DTSS-478]: https://outreach-io.atlassian.net/browse/DTSS-478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(deploy-to-dev): enable setting version

shell/lib/bootstrap.sh
oops, forgot this was also a required change so that each import can be read as a single line and pulled apart by jq. this change is back compatible with flat lists
=> fix: compress yq lines so that protoc-import-changes work

root/Makefile
When running in devspace, build should not be set up for dev/devenv as that's not available.
[XX-XX]
=> feat: Don't include or_dev when building in kubernetes

shell/validate.sh
=> feat: lintroller for oss

shell/build-jsonnet.sh, shell/deploy-to-dev.sh
Extract building jsonnet scripts into separate script so it can be reused in devspace config without the rest of deploy-to-dev.
[XX-XX]
=> feat: Extracted build-jsonnet.sh script

root/Makefile
Fix based on [this thread](https://outreach-hq.slack.com/archives/CN9MU7GLW/p1643761994266749?thread_ts=1643754880.060639&cid=CN9MU7GLW)
[XX-XX]
=> fix: Ensure `or_dev` is included when building locally

root/Makefile
=> fix(makefile): escape KUBERNETES_SERVICE_HOST

shell/ci/release/confluence-publish.sh, shell/ci/release/docs.sh, versions.yaml
* publish eligible markdown docs on merge into default branch
[XX-XX]
* circleci file changes - https://github.com/getoutreach/bootstrap/pull/954/commits/041964b4da18a10aaedf5739deb35cdc9a66c179
=> feat: publish confluence docs via ci

shell/ci/release/confluence-publish.sh
=> fix: edit warning

shell/ci/release/confluence-publish.sh
=> fix: use last tag

versions.yaml
=> fix: pick up v0.0.27 for a fix from markdowntools

versions.yaml
=> fix: Upgrade clerkgen's version

shell/ci/release/confluence-publish.sh
=> fix: regular expression for [DTSS-1299]

shell/golangci-lint.sh, versions.yaml
=> fix(validate): use custom golangci-lint for now

shell/fmt.sh
Run prettier for Markdown files
🙏 do I need to do some changes in bootstrap repo or these changes will populate automatically?
[XX-XX]
=> feat(prettier): format markdown files

shell/ci/testing/setup-devenv.sh
This fixes some issues with E2E being ran on local machines.
[XX-XX]
=> fix(ci/setup-devenv): skip some checks when outside of CI

shell/ci/release/confluence-publish.sh
* if this was the first tagged release this would fail because the
previous commit (the one from setup_repo) had no tags associated
with it.
[XX-XX]
=> fix: confluence publishing edge case

shell/devconfig.sh
=> fix: remove outreach cli reference

versions.yaml
* increases line buffer size
[XX-XX]
=> fix: update visualizemd version

shell/build-jsonnet.sh
With this change, the image registry passed in by `devenv` will be applied to bootstrap jsonnet files.
See https://github.com/getoutreach/bootstrap/pull/1061
[DTSS-1456]
=> feat: Added support for app image registry override

shell/ci/release/confluence-publish.sh, versions.yaml
=> feat: add mermaid support in publishing confluence docs

versions.yaml
=> fix: upgrade lintroller version

shell/devspace_start.sh
=> fix: Authenticate npm/yarn and bundler in dev container

root/Makefile, shell/debug.sh
Runs Delve in headless mode on set port so we can attach to it from VSCode.
[DTSS-1462]
[DTSS-1462]: https://outreach-io.atlassian.net/browse/DTSS-1462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(devspace): Enable remote debugging using vscode

shell/test.sh
This PR updates the go coverage command to calculate the coverage of all packages instead of just ones that contain a single test
[XX-XX]
=> fix(go): calculate coverage in ALL packages

versions.yaml
I recently added a keep-protos feature clerkgenproto, making it available in bootstrap thru devbase.
[QSS-1005]
=> fix: upgrade clerkgenproto to latest to get keep-protos feature

orbs/shared/commands/merge.yaml, orbs/shared/commands/upload_test_results.yml, orbs/shared/executors/testbed-docker.yml, orbs/shared/jobs/docker.yaml, orbs/shared/jobs/e2e.yaml, orbs/shared/jobs/finalize-coverage.yaml, orbs/shared/jobs/merge_into_release.yaml, orbs/shared/jobs/publish_docs.yaml, orbs/shared/jobs/release.yaml, orbs/shared/jobs/sync_package_hjson.yaml, orbs/shared/jobs/test.yaml, orbs/shared/jobs/test_node_client.yaml, shell/ci/release/release.sh
This PR adds a bunch of the jobs currently bootstrap into orb jobs so they can be easily reused in CircleCI.
[XX-XX]
=> feat(orb): move jobs into orbs

orbs/shared/jobs/release.yaml
This PR adds support for using a machine executor for the `release` job
[XX-XX]
=> feat(orb/jobs/release): support using machine executor

orbs/shared/jobs/release.yaml, orbs/shared/jobs/test.yaml
Small fixes for the devenv, already tested using the `dev:first` label.
[XX-XX]
=> fix(orb): misc fixes for devenv

root/Makefile
Air fixed issue with killing processes, but didn't release the fix yet.
[DTSS-1619]
[DTSS-1619]: https://outreach-io.atlassian.net/browse/DTSS-1619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Use latest air version with fix for process kill on mac

versions.yaml
This fixes issues with goimports and Go 1.18
[XX-XX]
=> fix(goimports): v0.1.10

shell/deploy-to-dev.sh
When deploying the service into devenv and the service was already deployed, things will fail if it had a job.
[DTSS-1582]
[DTSS-1582]: https://outreach-io.atlassian.net/browse/DTSS-1582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Delete jobs in namespace before deploying

shell/air-runner.sh
Cleaning up bootstrap as I delete the files for stencil, moving this into devbase where it _belongs_.
[XX-XX]
=> feat(shell): move air-runner to devbase

e2e/e2e.go
https://outreach-io.atlassian.net/browse/DTSS-1677
`make e2e` locally  runs e2e tests
=> feat: enable e2e test for library

e2e/e2e.go
addressed the comments of the PR https://github.com/getoutreach/devbase/pull/191
https://outreach-io.atlassian.net/browse/DTSS-1679
=> chore: e2e runner cosmetic changes

.github/workflows/create-bootstrap-pr.yaml
**What this PR does**: This PR adds a Github Action to create bootstrap PR on release.
=> feat: create bootstrap PR on release

orbs/shared/commands/save_go_cache.yml
=> fix: update golangci-lint cache in ci

shell/ci/release/confluence-publish.sh
I made a mistake while porting my local test script to devbase. This scopes the variable correctly so we can reference it.
[XX-XX]
=> fix(ci): scope previousTag correctly in confluence publish

versions.yaml
This is to bring in fixes for local development with clerk.
[DP-3485]
[DP-3485]: https://outreach-io.atlassian.net/browse/DP-3485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: bumping clerkgen version

.releaserc.yaml, package.json, yarn.lock
* use outreach version of orb publishing semantic release plugin
[XX-XX]
=> fix: releasing

package.json, yarn.lock
=> fix: upgrade orb release dep

.vscode/settings.json, orbs/shared/jobs/test.yaml, root/Makefile, shell/test.sh, shell/validate.sh
**What this PR does**: This PR removes all support for `or_int` and related functionality.
=> feat!: remove support for running or_int tests (DTSS-1887)

README.md
=> fix: release

shell/test.sh
Opening this PR another time to merge into the major release after the release this Sunday.
[DTSS-1369]
[DTSS-1369]: https://outreach-io.atlassian.net/browse/DTSS-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(test): shuffle and race tests

e2e/e2e.go
* this was merged into stencil-golang rc earlier
[XX-XX]
=> fix: prefer devenv.yaml over service.yaml

e2e/e2e.go, go.mod, go.sum
e2e uses vault CI address in CI
=> fix: e2e uses vault CI address in CI

orbs/shared/executors/testbed-machine.yml
**What this PR does**: This should fix issues with heroku
=> fix: update ubuntu image

e2e/e2e.go
**What this PR does**: Handles the scenario where a dep of a service requires flagship. We shouldn't fail at that level.
=> fix: handle deps requiring flagship

versions.yaml
Update clerkgen version to [1.23.1](https://github.com/getoutreach/clerkgen/releases)
[XX-XX]
=> fix: Update clerkgen version

orbs/shared/executors/testbed-machine.yml
Fixes issues w/ OpenSSL 3. This should contain the fixed Heroku APT repository in the machine as well.
[XX-XX]
=> fix(machine): downgrade to ubuntu 20.04

versions.yaml
Latest clerkgen release brings protooptions, we need the new protooptions to remove dependency on raw proto files in smartstore codegen and unblock proto move to clerkcommons.
[DP-00]
=> feat: update clerkgenproto to latest v1.24.0 for protooptions

e2e/e2e.go, shell/ci/release/docker.sh
**What this PR does**: This PR supports the new `service` argument in stencil. I also cleaned up the code to work better
=> fix: support new service tag in e2e (DTSS-2049)

e2e/e2e.go
=> fix: set arguments struct tag

shell/protoc.sh
TypeScript files are not generated anymore.
[XX-XX]
=> fix: generate typescript protobuf files (DTSS-2046)

e2e/e2e.go
We moved to `devenv.yaml` from `service.yaml`, this moves us to support that with the feature added in https://github.com/getoutreach/stencil-golang/pull/33
=> fix(e2e): use devenv.yaml for service info (DTSS-2049)

shell/ci/testing/setup-devenv.sh
This PR fixes https://app.circleci.com/pipelines/github/getoutreach/stencil-smartstore/8/workflows/7ca97238-1289-4503-932f-f7efd1daea80/jobs/20
[XX-XX]
=> fix(setup-devenv): asdf install

orbs/shared/executors/testbed-docker.yml, orbs/shared/jobs/test.yaml
* add the ability to define a custom docker image for jobs
[XX-XX]
=> feat: custom executor for shared/test

orbs/shared/jobs/test.yaml
* optional skip parameter to skip shared/test if supplied
[XX-XX]
=> feat: skip parameter in shared/test

orbs/shared/jobs/test.yaml
* if it doesn't have a step it fails to render config
[XX-XX]
=> fix: skip needs some sort of a step

versions.yaml
=> fix(DP-2294): pick up the latest clerkgenproto release for DP-2294

shell/devspace_start.sh
Adds the ability to run e2e tests through `devspace-start.sh`
[DTSS-1601]
[DTSS-1601]: https://outreach-io.atlassian.net/browse/DTSS-1601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add e2e command to devspace_start

versions.yaml
Updated clerkgenproto to [v1.25.2](https://github.com/getoutreach/clerkgen/releases/tag/v1.25.2)
[XX-XX]
=> fix(clerkgenproto): Update clekrgenproto version

shell/circleci/setup.sh, shell/lib/download-box.sh
* adds lib script to download box from remote url in ci
[XX-XX]
=> feat: download box in ci

shell/circleci/setup.sh, shell/lib/download-box.sh
This is an automatically generated release PR created by [`create-pr.sh`](https://github.com/getoutreach/dtss-tools/tree/main/release).
This PR should **NOT BE MERGED THROUGH THE GITHUB UI**, instead run `merge-release-prs.sh <repo>` instead.
=> chore(release): 07/25/22

e2e/e2e.go
=> fix: e2e runner skip submodules

shell/devconfig.sh
* don't hardcode VAULT_ADDRESS, use what is already there if it exists
and if it doesn't exist attempt to pull it from box config
[XX-XX]
=> fix: devserver vault address

shell/devconfig.sh
=> fix: devconfig lib path

orbs/shared/jobs/test.yaml
* aws region parameter to set AWS_REGION test env var
* built orb and validated it
[XX-XX]
=> feat: aws region as test env var

shell/lib/box.sh
This PR takes `lib/box.sh` from `main` and adds it to `release` to unbreak releases. This will merged back into `main` to fix the version calculation logic.
[XX-XX]
=> fix: add box library from main

versions.yaml
Update clerkgen version to use new clerkschema repository
[XX-XX]
=> feat: update clerkgen

shell/devspace_start.sh
Adds files to git so that tests can see that test file exits.
[XX-XX]
=> fix: add files to git for e2e tests

shell/ci/env/asdf.sh, shell/lib/asdf.sh
Fixes Go 1.17.9 errors in 1.18 repositories and speeds up asdf install.
[XX-XX]
=> fix: speed up asdf install, include .bootstrap

shell/ci/release/unstable-release.sh
=> fix(unstable-release): mark release as prerelease

shell/ci/release/unstable-release.sh
This allows unstable releasing to work on things without `comands`, e.g. native extensions.
[XX-XX]
=> fix(release/unstable): remove commands check

shell/ci/env/asdf.sh, yarn.lock
This PR fixes a race condition with the plugin list caching added to `asdf.sh` in the #301, now we change the ordering of the `source` to have this work properly.
[DT-2808]
[DT-2808]: https://outreach-io.atlassian.net/browse/DT-2808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ci/env/asdf): fix race condition in plugin list

root/Magefile.go
This PR fixes plugins not being built
[DT-2828]
[DT-2828]: https://outreach-io.atlassian.net/browse/DT-2828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(mage): properly build plugins

root/Magefile.go, shell/lib/asdf.sh
Promote unstable to rc, created by `dt release create`
=> Promote unstable to rc

root/go.go, shell/devspace_start.sh, shell/lib/box.sh
This PR ensures that devspace downloads the box configuration for the dev container
[DT-2843]
[DT-2843]: https://outreach-io.atlassian.net/browse/DT-2843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(devspace): download box config

shell/fmt.sh, shell/lib/asdf.sh, shell/lib/bootstrap.sh
Promote rc to stable, created by `dt release promote`
=> Promote rc to stable

versions.yaml
Should fix issues with Go 1.19
[DT-2808]
[DT-2808]: https://outreach-io.atlassian.net/browse/DT-2808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(delve): upgrade to v1.9.1

README.md
https://github.com/getoutreach/stencil-circleci/pull/36
[DT-2841]
[DT-2841]: https://outreach-io.atlassian.net/browse/DT-2841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: prepare to archive

shell/lib/shell.sh
=> fix: set exit code properly

shell/lib/shell.sh
Promote unstable to rc, created by `dt release promote`
=> chore: Promote unstable to rc

versions.yaml
* hopefully adds support for blockquotes
* https://outreach-hq.slack.com/archives/CN9MU7GLW/p1666395186572429
[XX-XX]
=> fix: update getoutreach/markdowntools/visualizemd

e2e/e2e.go, scripts/golangci.yml, service.yaml
https://outreach-io.atlassian.net/browse/DT-2869
=> fix: Update devbase to pass OpsLevel Platinum level

orbs/shared/executors/testbed-machine.yml, shell/circleci/machine.sh
Hotfixes commit "79a7d94448810c6d125f106ab34ffead36cb887d" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 79a7d94448810c6d125f106ab34ffead36cb887d into channel stable

versions.yaml
Bumps markdowntools version to add support for blockquotes.
[XX-XX]
=> fix: Bumping up markdowntools

shell/protoc.sh
* make protoc work relative to the current working directory as opposed
to just hardcoded to /api
[XX-XX]
=> feat: multitarget protoc

versions.yaml
=> fix: Bump markdowntools to v0.0.33

shell/protoc.sh
This was the only path to make this change non breaking. This approach simply make the process of copying `.pb` files automatic.
This approach places the files in the same location as repos currently expect them to be. I tried many different approaches to getting things to import from other locations and none seemed to work. The common consensus on the node grpc plugin issues list is to follow the same process as well. 
[DT-2822]
[DT-2822]: https://outreach-io.atlassian.net/browse/DT-2822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(prtoc): copy imported pb files

shell/protoc.sh
Proto files cannot have circular dependencies (protoc fails), but we generally have circular dependencies in our domain and we need to represent it in our gRPC endpoints.
ProtoAPI for this purpose introduced `reference` messages which contain just the IDs and therefore can be cross-referenced. E.g.:
```
Prospect -> AccountRef
Account -> repeated ProspectRef
```
This reference messages are placed in subdirectory of `api` so they can reside in separate go package and be imported properly.
This PR adds support to process subdirectory in workDir (`api`).
[RMS-1527]
[RMS-1527]: https://outreach-io.atlassian.net/browse/RMS-1527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(protoc): support for processing subdirectory

docs/README.md, docs/makefile.md
Title says, it does :D
[DT-3189]
Next PR https://github.com/getoutreach/stencil-base/pull/82
[DT-3189]: https://outreach-io.atlassian.net/browse/DT-3189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add some basic docs (DT-3189)

.circleci/config.yml, opslevel.yml, service.yaml, stencil.lock
Re-stencils in order to test release.
[XX-XX]
=> fix: re-stencil

.circleci/config.yml, service.yaml, stencil.lock
Manually remove stencil-discovery so it stops being a dependency.
[DT-3385]
[DT-3385]: https://outreach-io.atlassian.net/browse/DT-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: remove stencil discovery

.circleci/config.yml, CONTRIBUTING.md, monitoring/slos.tf, service.yaml, stencil.lock
Uses rc versions that do not depend on `stencil-discovery`.
[DT-3385]
[DT-3385]: https://outreach-io.atlassian.net/browse/DT-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: dependencies without discovery

.tool-versions, versions.yaml
Bumps tooling versions.
[DT-3447]
[DT-3447]: https://outreach-io.atlassian.net/browse/DT-3447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update tool versions

shell/linters/jsonnet.sh
=> fix: correct version in jsonnet.sh downloading jsonnetfmt

versions.yaml
=> fix: correct jsonnetfmt version

.tool-versions
until https://github.com/golangci/golangci-lint/issues/3086 is fixed
[XX-XX]
=> fix: downgrade golangci-lint to 1.50.0

shell/devspace_start.sh
trust /home/dev/app in devspace
https://outreach-io.atlassian.net/browse/DT-3465
=> fix: trust /home/dev/app in devspace

docs/linters.md
Add doc explaining why we are returning the value 1 in linter functions
[XX-XX]
=> chore(doc): add linter doc

shell/devspace_start.sh
Hotfixes commit(s) "4a199806b59e1dcdc5365e67b5e03a220ead8870" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 4a199806b59e1dcdc5365e67b5e03a220ead8870 into channel stable

shell/devconfig.sh
Hotfixes commit(s) "13e0d6a094c0aa695f9f3ee15a86e6764738954a" into channel rc, created by `dt release hotfix`
=> chore: Hotfix 13e0d6a094c0aa695f9f3ee15a86e6764738954a into channel rc

shell/ci/release/release.sh
* incorrectly stepping back two directories
[XX-XX]
=> fix: source bootstrap lib path

shell/ci/release/release.sh
* erronously adding lib to a path that already had lib in it
[XX-XX]
=> fix: release script bootstrap lib directory

.circleci/config.yml, .vscode/launch.json, go.mod, package.json, service.yaml, stencil.lock, yarn.lock
PR of stencil run post-release
[XX-XX]
=> feat: restencil

package.json, yarn.lock
Adds the circle orb back. Should this be added to stencil-base?
[XX-XX]
=> feat: add circle orb back

shell/circleci/machine.sh
Hotfixes commit(s) "ebf84de8c730d48b4a3606dc93041a51b2eeb733" into channel stable, created by `dt release hotfix`
=> chore: Hotfix ebf84de8c730d48b4a3606dc93041a51b2eeb733 into channel stable

shell/ci/testing/setup-devenv.sh
Kubernetes' API key got changed, so here we go (again): https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585
[XX-XX]
=> fix(ci): update kubectl apt key

shell/ci/testing/setup-devenv.sh
This version was missed during the Global Upgrade(TM) and happened to notice it, so upgrading it
[XX-XX]
=> fix(ci): install kubecfg v0.28.1

go.mod, go.sum, root/Magefile.go, root/go.go
This PR unbreaks builds when a box config doesn't exist on a user's local machine.
[XX-XX]
=> fix(box): support building without box config

.tool-versions
Fixes some small bugs that might help with generics issues
[XX-XX]
=> fix(golangci-lint): 1.51.2

versions.yaml
Updates the Github Markdown -> Confluence publishing code to use a newer version of [mark](https://github.com/kovetskiy/mark/releases)
[XX-XX]
=> fix(confluence): update mark

root/checkopslevel.go, root/opslevel/opslevel.go, root/opslevel/opslevel_test.go
- handle NPE
- revise error messages and add log for readability
** no service entry found in opslevel **
** there's an entry but no lifecycle is assigned in opslevel **
** service maturity does not meet the requirement **
**requirement**: https://outreach-io.atlassian.net/browse/DT-2954
**bug fix**: https://outreach-io.atlassian.net/browse/DT-3563
=> fix: handle NPE and revise error messages

shell/circleci/machine.sh
Conditionally installs amd64 or arm64 gh cli instead of always amd64
[XX-XX]
=> fix: Install gh for arm

shell/ci/release/release.sh
Hotfixes commit(s) "e436c7c6be58d43396974e3852a6c2fa34e05f02" into channel rc, created by `dt release hotfix`
=> chore: Hotfix e436c7c6be58d43396974e3852a6c2fa34e05f02 into channel rc

root/checkopslevel.go
=> fix: correct opslevel error message

shell/opslevel/upload_prismaci.sh, shell/security/prismaci/twist-scan.sh
Clarify the purposes of scripts related to Twistlock and remove an invalid argument from a twistcli command to ensure that twistcli scans don't randomly break in the future
[XX-XX]
=> chore: Update twistlock comments and argument

shell/opslevel/upload.sh
Clarifying a comment in a script to eliminate any confusion.
[XX-XX]
=> Clarify scan results destination

shell/lib/asdf.sh
Previously, we'd always install amd64 versions of binaries if `asdf install` failed. This was our only way to determine if a binary was not compatible with `darwin/arm64`. However, since then, we've moved away from anything needing amd64 compat, and the few that do we install with `orc setup`. As such, I've removed the automatic handling of this and replaced it with a note.
We've had a few users have the step fail due to network flakiness, or other issues, and get the amd64 version without knowing. This is problematic for many reasons, so that's the main motivation of this change.
[XX-XX]
=> fix(asdf): dont automatically install amd64 versions

.circleci/config.yml, .gitignore, scripts/devbase.sh, stencil.lock
Post release run of stencil
[XX-XX]
=> feat: run stencil

orbs/shared/jobs/e2e.yaml
Hotfixes commit(s) "c5d5d8110afa3efd2e31dcaa8e241942028da7ea" into channel stable, created by `dt release hotfix`
=> chore: Hotfix c5d5d8110afa3efd2e31dcaa8e241942028da7ea into channel stable

e2e/e2e.go
- Delegate app dependency calculation to devenv
- Devenv PR to synch dependency calculation - https://github.com/getoutreach/devenv/pull/561
- The goal is speedup app deps deployment by waiting for pods to be ready at the end, which this change unlocks - https://github.com/getoutreach/devenv/pull/568
[QF-822]
[QF-822]: https://outreach-io.atlassian.net/browse/QF-822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: use devenv to calculate app dependencies

shell/build-jsonnet.sh, shell/deploy-to-dev.sh
This fixes an issue with devbase.yaml calling `build-jsonnet.sh` not parsing the correct dev_email.
[XX-XX]
=> fix: simplify exported environmental variables

shell/opslevel/upload_prismaci.sh
Hotfixes commit(s) "3bc9520922d7025559bc06a86c2495e9898858b4" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 3bc9520922d7025559bc06a86c2495e9898858b4 into channel stable

shell/ci/testing/setup-devenv.sh
Hotfixes commit(s) "d852f99189aea15a715f0e8f02dfef32d05b16e1" into channel stable, created by `dt release hotfix`
=> chore: Hotfix d852f99189aea15a715f0e8f02dfef32d05b16e1 into channel stable

shell/ci/testing/setup-devenv.sh
Hotfixes commit(s) "8894742cc609432277bfa619e57dda3603ec2541" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 8894742cc609432277bfa619e57dda3603ec2541 into channel stable

orbs/shared/executors/testbed-machine.yml
Updates the CircleCI executor as per https://circleci.com/developer/machine/image/ubuntu-2204
[XX-XX]
=> fix(executor/testbed-machine): update ubuntu image

shell/opslevel/upload.sh, shell/opslevel/upload_prismaci.sh
=> fix(prisma): script not retrying upload when artifact not found

shell/devspace_start.sh
Changes the devspace start script to ensure that asdf runtimes are
installed before starting anything (e.g., `make dev`, `make e2e` or
dropping the user into a shell). This reduces the percieved compilation
time since this would otherwise be done lazily on the first `make`
invocation. This is especially important/useful for an upcoming
stencil-golang PR that changes the cache behaviour of `asdf`.
Also changed the bundle authentication to not require `ruby` as `bundle`
is not always available at the time.
=> feat(devspace): ensure that asdf installs are installed before starting

shell/ci/release/docker.sh
Hotfixes commit(s) "4372b1f" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 4372b1f into channel stable

shell/ci/release/docker.sh, shell/ci/release/docker_test.sh, shell/ci/release/testdata/test.yaml, shell/lib/yaml.sh, shell/lib/yaml_test.sh
Hotfixes commit(s) "ca26c022fa75d4e4aed279937fdcee23e31bf926" into channel rc, created by `dt release hotfix`
=> chore: Hotfix ca26c022fa75d4e4aed279937fdcee23e31bf926 into channel rc

.circleci/config.yml, .vscode/launch.json, CONTRIBUTING.md, go.mod, go.sum, package.json, scripts/golangci.yml, stencil.lock, yarn.lock
=> feat(stencil): restencil

package.json
We should also open a ticket to fix this.
[XX-XX]
=> fix(circleci): add back outreach semantice release orb

shell/air-runner.sh, yarn.lock
Fix suggested devenv parameter
[QF-880]
[QF-880]: https://outreach-io.atlassian.net/browse/QF-880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: devspace related message

.tool-versions, shell/shfmt.sh, yarn.lock
Updates `shfmt` for  hygiene reasons.
Changes the comment for `shfmt.sh` to better reflect the fact it uses
asdf now.
=> feat: update shfmt

e2e/e2e.go
- In order to support E2E testing of CLI app based on CLI interface we need to have build application in make e2e step
[QF-877]
[QF-877]: https://outreach-io.atlassian.net/browse/QF-877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Build CLI application in make e2e

docs/makefile.md, e2e/e2e.go, orbs/shared/jobs/e2e.yaml, shell/ci/release/docker.sh
Promote rc to stable, created by `dt release promote`
=> chore: Promote rc to stable

root/Makefile
=> fix: Don't echo comment.

docs/linters.md, shell/fmt.sh, shell/linters.sh
Hotfixes commit(s) "e751ae3e2ccd6675cfd959560ef7a271a8bf566d, b00fdefb0bf8c9e535b3d6371967372897ab6ee8" into channel stable, created by `dt release hotfix`
=> chore: Hotfix e751ae3e2ccd6675cfd959560ef7a271a8bf566d into channel stable

shell/ci/auth/github_packages.sh
Currently, you can manually specify `GITHUB_TOKEN` for `auth/github` but
not for `auth/github_packages`. While, I would like to make calling
`auth/github` just a requirement for `auth/github_packages`, that seems
breaking. So, instead, we just match the behaviour of `auth/github` and
allow using `GITHUB_TOKEN` if set.
This is useful for repos that manually use pieces of devbase (for
example, Outreach's flagship) that may not have things like Go installed
yet.
=> feat(auth/github_packages): support setting GITHUB_TOKEN

go.mod, go.sum
Hotfixes commit(s) "d5f4ab845e8d66d4e57fd140ed6f131d0f6e0b1e" into channel rc, created by `dt release hotfix`
=> chore: Hotfix d5f4ab845e8d66d4e57fd140ed6f131d0f6e0b1e into channel rc

shell/circleci/machine.sh
Adds support for newer versions of Ubuntu and Debian by using the `yq`
apt package, if it's available, and falling back to `pip3` if it's not.
Cleans up the code a bit to make it easier to determine what version of
`gh` is in use/desired. Updates to `v2.32.1`. This will be used by
`bootstrap/dev` in an upcoming PR.
=> feat(machine): support newer versions of Ubuntu

shell/ci/env/asdf.sh
Updates asdf to `v0.12.0` in CI. We already use this version pretty much everywhere.
=> feat(ci): asdf 0.12.0

shell/ci/env/asdf.sh
Hotfixes commit(s) "e99388ebb84820c40a8a7ad6a5d8e7964aec489c" into channel stable, created by `dt release hotfix`
=> chore: Hotfix e99388ebb84820c40a8a7ad6a5d8e7964aec489c into channel stable

orbs/shared/commands/with_node_client_cache.yml
Hotfixes commit(s) "8f298fa86e5ff37afc75f6c6eeda14275f758f25" into channel stable, created by `dt release hotfix`
=> chore: Hotfix 8f298fa86e5ff37afc75f6c6eeda14275f758f25 into channel stable

.circleci/config.yml, shell/ci/testing/delibird.sh, shell/ci/testing/setup-devenv.sh
Ensures that the delibird CLI has an authentication token configured.
=> fix(delibird): fetch delibird token

orbs/shared/executors/testbed-machine.yml, shell/ci/release/docker.sh, shell/lib/buildx.sh
Enabling Docker Layer Caching to reduce time of build pipelines. Basically now it downloads and compiles dependencies with every build (even in PRs), this should reduce time of builds when there are no changes in dependencies.
[XX-XX]
=> feat: Enable docker layer caching

orbs/shared/jobs/docker_stitch.yaml
=> fix(orb): docker stitch needs machine: true

shell/ci/release/docker-stitch.sh, shell/ci/release/docker.sh, shell/lib/buildx.sh, shell/lib/docker.sh, shell/lib/docker_test.bats
Does as it says on the tin.
[DT-3606]
I moved `get_image_field` into its own library file, so I moved its corresponding tests plus got rid of the `TESTING_DO_NOT_BUILD` env var hack.
I also extracted the logic to generate `docker buildx` args into its own function and added tests.
[DT-3606]: https://outreach-io.atlassian.net/browse/DT-3606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ci): handle the case where multiple images are defined for a given service

shell/ci/release/docker.sh
#698 introduced a couple of regressions, this PR fixes it.
[DT-3606]
[DT-3606]: https://outreach-io.atlassian.net/browse/DT-3606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(docker): fix regressions from refactoring

shell/ci/testing/coverbot/upload-coverage.sh
Updates `coverbot` to `v1.0.1` to get the latest improvements.
=> feat(coverbot): v1.0.1

shell/linters/kubecfg.sh, versions.yaml
=> feat: bump kubernetes version for kubeconform

package.json, yarn.lock
=> fix: add back semantic-release-circleci-orb

versions.yaml
=> fix: upgrade ruby-grpc-tools to 1.62.0

shell/yq.sh
=> fix(yq): force gojq if go yq is installed

package.json, yarn.lock
=> chore: revert semantic-release dependency bumps

shell/ci/testing/coverbot/upload-coverage.sh
I'd propose to update version of coverbot being used (hope it's a proper place to update the version).
[XX-XX]
=> feat(coverbot): update version of coverbot to v1.0.5

shell/linters/kubecfg.sh
- update kubeconform to 0.6.4
[XX-XX]
=> fix: bump kubeconform to 0.6.4

orbs/shared/jobs/pre-release.yaml
=> chore(orb): fix typo

orbs/shared/commands/build_node_client.yml, orbs/shared/jobs/test_node_client.yaml
Also standardizes step names.
[DT-4426]
[DT-4426]: https://outreach-io.atlassian.net/browse/DT-4426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(orbs): build Node.js gRPC client before testing it

shell/docker-build.sh
Fixes a regression from #808 where some code was erroneously copy-pasted.
[DT-4504]
[DT-4504]: https://outreach-io.atlassian.net/browse/DT-4504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(docker-build): remove broken, unnecessary code

shell/lib/docker.sh, shell/lib/docker_test.bats
Invert incorrect logic and add regression tests.
=> fix(docker): correct pull registry fallback logic

shell/gobin.sh
=> fix: upgrade gobin to 1.11.12

.circleci/config.yml, go.mod, go.sum, shell/gobin.sh, stencil.lock, yarn.lock
Merge tmp-release-stable-v2.29.1-rc.2 to release
=> chore: Release v2.29.1

shell/ci/release/docker-authn.sh, shell/circleci/install_gh.sh, shell/lib/github.sh, shell/lib/mise.sh, versions.yaml
Merge tmp-release-stable-v2.29.2-rc.1 to release
=> chore: Release v2.29.2

shell/ci/env/asdf.sh
Merge tmp-release-stable-v2.29.3-rc.1 to release
=> chore: Release v2.29.3

versions.yaml
Merge tmp-release-stable-v2.29.4-rc.1 to release
=> chore: Release v2.29.4

orbs/shared/commands/build_docker_image.yml, orbs/shared/commands/stitch_docker_image.yml, orbs/shared/jobs/docker_amd64.yaml, orbs/shared/jobs/docker_arm64.yaml, orbs/shared/jobs/docker_stitch.yaml, shell/ci/release/docker-stitch.sh, shell/lib/bootstrap.sh, shell/lib/bootstrap_test.bats, shell/lib/docker.sh, shell/lib/docker_test.bats
=> feat: support deployments with SHA versioning

shell/ci/release/docker-stitch.sh
=> fix: due to incorrectly checked condition, images were pushed on dry-run

orbs/shared/commands/stitch_docker_image.yml, orbs/shared/jobs/docker_stitch.yaml, shell/lib/docker.sh, shell/lib/docker_test.bats
Accommodate condition checks to format in which CircleCI passes boolean parameters to env variables
[XX-XX]
=> fix: avoid using CircleCI boolean params

orbs/shared/jobs/publish_docs.yaml, orbs/shared/jobs/test_node_client.yaml
[DT-4466]
[DT-4466]: https://outreach-io.atlassian.net/browse/DT-4466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(orb): add custom executor support to test_node_client

shell/ci/auth/github_packages.sh
Needed to migrate the `actions` repository to GHCR.
[DT-4707]
[DT-4707]: https://outreach-io.atlassian.net/browse/DT-4707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(docker): log into GitHub Packages

shell/lib/github.sh
=> fix(github): better mise-installed detection for gh

shell/ci/auth/github.sh, shell/ci/release/docker-authn.sh, shell/ci/testing/setup-devenv.sh, shell/circleci/machine.sh, shell/circleci/setup.sh, shell/lib/github.sh, shell/lib/mise.sh, shell/yq.sh
Sometimes downloading mise or its install script fails, we need to account for that.
[DT-4766]
[DT-4766]: https://outreach-io.atlassian.net/browse/DT-4766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(mise): attempt multiple times to install mise itself

go.mod, go.sum, shell/build-jsonnet.sh, shell/ci/auth/github.sh, shell/ci/release/docker-authn.sh, shell/ci/testing/setup-devenv.sh, shell/circleci/machine.sh, shell/circleci/setup.sh, shell/lib/github.sh, shell/lib/mise.sh, shell/yq.sh
Merge tmp-release-stable-v2.32.0-rc.3 to release
=> chore: Release v2.32.0

e2e/e2e.go
Order of operations was wrong, assume that `devenv` would be in `PATH` rather than it's installed by `mise` *and* `PATH` wasn't updated.
Get rid of the `mise not found` check, since there's no longer any code to fall back to.
[DT-4771]
[DT-4771]: https://outreach-io.atlassian.net/browse/DT-4771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(e2e): check PATH for devenv before mise

shell/ci/release/dryrun.sh, shell/ci/release/pre-release.sh, shell/ci/release/release.sh, shell/ci/release/trigger-rc-release.sh, shell/lib/github.sh, shell/lib/mise.sh
Standardizes GitHub token fetching (and also standardizes finding `gh`).
[DT-4776]
[DT-4776]: https://outreach-io.atlassian.net/browse/DT-4776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(github): add github_token convenience function

shell/ruby/publish.sh
=> refactor(ruby/publish): use org from box config, fix up logging

shell/build-jsonnet.sh, shell/ci/testing/delibird.sh, shell/lib/github.sh, shell/lib/mise.sh, shell/yq.sh
The function was duplicated in multiple places, ad-hoc.
Should be easy to add uses of it as necessary throughout `shell/`.
=> fix: consolidate finding mise-installed tools into a single function

shell/ci/release/dryrun.sh
This allows repos which can have new major versions properly detect branches with breaking changes.
=> fix(release-dryrun): analyze with a combined commit message from all commits in the branch

shell/linters/prettier.sh
The tool in mise is `npm:prettier`.
=> fix(prettier): typo in error message

.circleci/config.yml, .gitmodules, go.mod, go.sum, mise.lock, mise.toml, orbs/shared/executors/testbed-machine.yml, orbs/shared/executors/testbed-macos.yml, orbs/shared/jobs/test.yaml, scripts/bash-test-runner.sh, shell/ci/env/asdf.sh, shell/ci/release/dryrun.sh, shell/ci/release/pre-release-dryrun-gha.sh, shell/ci/testing/setup-devenv.sh, shell/circleci/machine.sh, shell/devconfig.sh, shell/devspace_start.sh, shell/docs-build.sh, shell/golangci-lint.sh, shell/lib/bootstrap_test.bats, shell/lib/github_test.bats, shell/lib/mise.sh, shell/lib/sed.sh, shell/lib/sed_test.bats, shell/lib/shell.sh, shell/lib/shell_test.bats, shell/lib/test_helper.sh, shell/linters/go.sh, shell/test.sh
Merge tmp-release-stable-v2.34.0-rc.3 to release
=> chore: Release v2.34.0

shell/linters/prettier.sh
=> fix(prettier): check for package.json before using it with gojq
