- shell/deploy-to-dev.sh
**What this PR does / why we need it**:   Plumbs LD_DEV_EMAIL
**JIRA ID**: DT-0
The flagship client supports an env var LD_DEV_EMAIL.  When this is specified, all Launch Darkly requests include this as a custom flag value.  This allows feature flags to be changed for specific dev env hosts.
This PR adds a similar setup (but using DEV_EMAIL and dev_email so that this can be used in more places than just LD).  Also the `DEV_EMAIL` env var is just an override with the default being `git config user.email`
The plan is to make the following changes (all in separate repos sadly) to support this:
1. Update the bootstrapped fflags.yaml jsonnet to use `std.extVar('dev_email')` so that the env var gets picked up by bootstrapped services automatically.
2. Update flagship …
> feat: plumb LD_DEV_EMAIL env var to support LD variations based on dev email

- shell/lib/bootstrap.sh
Resource versions query in bootstrap lib currently returns `null` for non-existent resources which leads test script to setup non-existent containers. This PR adds a fix to the mentioned query.
> fix: return proper resource version

- root/Makefile
Current [CI pipelines](https://app.circleci.com/pipelines/github/getoutreach/orexservice/472/workflows/b6ce4fc9-d8b4-4578-b874-840e5ae12501/jobs/2164) are failing in `release-dryrun` step when a minor release is triggered.
Turns out `goreleaser` bumped up one of its [dependencies](https://github.com/goreleaser/goreleaser/commit/be93544e5ccb82735da3cc133d75d96801e9b1ea#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R18) in [v0.158.0](https://github.com/goreleaser/goreleaser/releases/tag/v0.158.0). From version [v1.0.0](https://github.com/goreleaser/fileglob/pull/17), such dependency started to use the pkg `io/fs`. This pkg is part of the standard library in Go 1.6.
> fix: downgrade goreleaser version

- root/Makefile
- shell/debug.sh
- versions.yaml
**What this PR does / why we need it**:  This adds a debug script that was omitted when we moved the repository scripts to this repo. It also adds a helpful `make debug` command which works similarly to `make devserver`.
**JIRA ID**: DT-00
**Notes for your reviewer**: I did a quick smoke test on an example repository to make sure that delve actually ran. (The old, deleted version did not work with the recent gobin script).
> feat: add debug script from bootstrap

- shell/devconfig.sh
This PR changes the `get_vault_secrets` function in devconfig.sh to only remove trailing newlines
**JIRA ID**: [DT-316]
[DT-316]: https://outreach-io.atlassian.net/browse/DT-316
> fix: update get_vault_secrets to only remove trailing newline

- root/Makefile
**What this PR does / why we need it**:   Add pre and post action support to Makefile
**JIRA ID**: DWF-5884
This adds support for individual repos to add pre and post actions to targets that were meaningful and not internal.
The pre action is via a `pre-xyz` target.  The post action is just using the [double-colon](https://www.gnu.org/software/make/manual/html_node/Double_002dColon.html) support in make.
> feat: add pre-action steps and use double-colon to Makefile

- shell/docker-builder.sh
- shell/security/prismaci/twist-scan.sh
This PR is the first to support [DT-509]: re-enable image scan in bootstrap and move twist-scan shell from prismaci repo into devbase to run in machine-mode on a bare VM itself. The original script was slightly modified to support twistcli download shortly before running the scan (and I removed the curl -k flag that could cause security issues - it should not be needed).
**JIRA ID**: [DT-509]
This PR has been tested by faking bootstrap: devenv to point to private branch + temporary removing CIRCLE_TAG block to enable scan on all runs (and not just release/tags).
[DT-509]: https://outreach-io.atlassian.net/browse/DT-509
[DT-509]: https://outreach-io.atlassian.net/browse/DT-509
> fix(prismaci): copy image scanner from prismaci repo into devbase and reenable it

- shell/shellcheck.sh
**What this PR does / why we need it**: There are no arm64 builds of shellcheck at the moment, so we need to use the amd64 version on darwin/arm64. 
**JIRA ID**: DT-0
> fix: use AMD64 version of shellcheck on M1

- root/Makefile
**What this PR does / why we need it**:   Add missing env vars in Makefile e2e target
**JIRA ID**: DT-00
`make e2e` used to set these env vars before.  Bring them back again. Note that these env vars seem to be properly propagated ([here](https://github.com/getoutreach/devbase/blob/3dd46c19912d4e693a1ec0f6e1ac6770132a1aa5/shell/e2e.sh#L14)) already.
> feat: add missing env vars in Makefile e2e target

- shell/fmt.sh
**What this PR does / why we need it**: This fixes a formatting bug where `eslint` may have formatting changes (such as import order) but `make fmt` doesn't apply them, which means that rebootstrapping reverts the changes.
See, for example, https://github.com/getoutreach/authz/pull/465
**JIRA ID**: DTSS-00
> feat(fmt): run eslint --fix on the Node.js API client

- shell/docker-builder.sh
Add the NPM_TOKEN environment variable as a Docker build secret. This
value is available in CircleCI when the `npm-credentials` context is
applied to the build step. It is also available in the development
environment.
**JIRA ID**: VXP-2691
See related PR to add the npm-credentials context in the CircleCI config: https://github.com/getoutreach/bootstrap/pull/613
> feat: add NPM_TOKEN as a docker build secret

- shell/lib/buildx.sh
Update buildx so that docker build can accept secrets from environment
variables.
> fix: update buildx

- shell/protoc.sh
grpc-node packages have been deprecated since Apr 2021, this PR updates all the js packages to rely on @grpc/grpc-js instead. 
1.37_2 is newer than the 'latest' tag image.
**JIRA ID**: DT-355
> feat(grpc-js): upgrade our grpc protoc tools to 1.37_2

- shell/lib/bootstrap.sh
- shell/protoc.sh
These changes allow settings service to move forward with leveraging
settings payloads defined in the `schema` repo directly in the settings
service.
**JIRA ID**: [OLM-952]
Also of note: This only account for generating the pb code within
the repo itself. It won't generate the imported code, that step needs to
be done manually for the service and it's clients
Generation tested manually with and without imports
Example:
```
go-protoc-imports:
- "github.com/org/repo@latest"
```
[OLM-952]: https://outreach-io.atlassian.net/browse/OLM-952
> feat(OLM-952): support importing proto files from schema repo

- shell/protoc.sh
Allows generating `<file>.pb.validate.go` files with https://github.com/envoyproxy/protoc-gen-validate, this is useful for the settings service which operates on protobuf definitions. As the service is largely generic on the inside, having a means to define constraints (validation rules) on the messages themselves is tremendously useful in enabling a broad set of validation cases for settings groups.
**JIRA ID**: [OLM-952]
[OLM-952]: https://outreach-io.atlassian.net/browse/OLM-952
> feat(OLM-952): support validation flag to enable protoc-gen-validate

- shell/gobin.sh
**What this PR does / why we need it**: This PR does what the title says. Instead of using, the now archived, older gobin to bootstrap this one, we now directly download it. Using the older gobin resulted in 3-4s latency being added on print binary path calls for no apparent reason. Calling gobin directly is faster and removes that component. 
> fix(gobin): directly download gobin

- shell/docker-builder.sh
**What this PR does / why we need it**: This PR makes twist scan fails a non-blocking event.
**JIRA ID**: [DT-0]
**Notes for your reviewer**: [**Internal Context**](https://outreach-hq.slack.com/archives/CN9MU7GLW/p1628006855068600)
> fix: don't fail entire docker image build on scan fail

- shell/docker-builder.sh
**What this PR does / why we need it**: we need OpsLevel report on released images, yet we only scanned and produced them for PRs.
**JIRA ID**: [DTSS-509]
[DTSS-509]: https://outreach-io.atlassian.net/browse/DTSS-509
> fix(opslevel): Always scan images to ensure opslevel report is sent on releases

- shell/codeowners-validator.sh
- shell/validate.sh
- versions.yaml
This is largely an RFC. For context, there was a minor incident where a CODEOWNERS file was accidentally modified and committed to the default branch with invalid syntax, so none of the code owners were properly notified when PRs were created. As a result, I've added [codeowners-validator](https://github.com/mszostok/codeowners-validator) to the list of linters.
**JIRA ID**: DTSS-00
I've added rudimentary support for GitHub token checking. Also, there are some hardcoded org name assumptions which need to be addressed, for which I could use some guidance.
> feat(validate): add validator for GitHub CODEOWNERS file

- root/Makefile
**What this PR does / why we need it**: Looks like older versions skip Go 1.17 in their < 1.16 check, so we upgrade to fix that and restore support for Go 1.17 darwin/arm64 builds.
> fix: update goreleaser to support go 1.17 darwin/arm64

- shell/clerkgenproto.sh
- versions.yaml
This PR add `clerkgen.sh`. This will run from bootstrap as part of `gogenerate`. Command will look like this:
```
//go:generate ../scripts/shell-wrapper.sh clerkgenproto.sh --sn outreach.application.twilio_recording_del_req --sn outreach.tutorial.tutorial_event --od . -l go
```
In the above command, the schema names will be replaced as per the user's configuration. 
**JIRA ID**: DP-2355
**Testing**:
1. `chmod +x clerkgenproto.sh` <- Hoping this happens automagically when an user runs `bootstrap`
2. `./clerkgenproto.sh --sn outreach.application.twilio_recording_del_req --sn outreach.tutorial.tutorial_event --od . -l go`
Generated all types as expected. Output:
```
INFO[0000] Starting clerkgen for protobuf
Generating proto clients
Generating go …
```
> feat: [DP-2355] Add clerkgen.sh

- shell/fmt.sh
I noticed that during `make fmt`, `shfmt` was formatting files in devbase, which is a waste of computing power since that folder gets regenerated every time the devbase version changes.
N/A
That being said, `validate.sh` should run on this repo in CI so that shfmt wouldn't rewrite the files to begin with.
> fix(fmt): don't format shell files in .bootstrap

- shell/devconfig.sh
This PR moves the merging of configuration functionality in local development. Instead, users should be modifying the `<appName>.config.jsonnet` file instead, which is more deterministic and compatible with the Tilt world we'll be going to soon. Users should use `make devserver` to ensure their changes are always reflected locally.
[**CONTEXT**](https://outreach-hq.slack.com/archives/CN9MU7GLW/p1628786338329700)
> fix: remove merging of configuration

- shell/ci/testing/sync-package-hjson.js
The Dependabot updater failed silently because the script moved from `shell/circleci` to `shell/ci/testing`.
N/A
Also added some debug info to the log for easier troubleshooting in the future.
> fix(sync-package-hjson): update relative path due to the script moving

- root/Makefile
We don't care about dirty state in CI because we don't fully use goreleaser except to generate archives, so just stop this from causing problems. Forever.
Also updates goreleaser because we can.
[XX-XX]
> fix: ignore dirty git state w/ goreleaser

- root/Makefile
- shell/devspace_start.sh
* Add [air](https://github.com/cosmtrek/air) as file watcher
* Add `devspace_start.sh` as entry point in devspace container. When this runs, it adds the `asdf` sourcing to `~/.bashrc`, sets up `gh` as git creds provider (`gh` is automatically authenticated as we set `GH_TOKEN` env variable for devspace container). This way, when you run `devspace dev` you can immediately do `make` or `make dev` and it will run, pull modules, ...
[XX-XX]
`.air.toml` requires app specific binary name, so it's generated by bootstrap
> feat: Added devspace container start script and make dev for watcher

- shell/ci/testing/coveralls-finish.sh
- shell/ci/testing/coveralls.sh
This allows, for example, uploading both unit test and end-to-end test code coverage to coveralls and have it merge appropriately.
[TAU-1223]
Each test job will run goveralls, and then a finisher job will run when all test jobs complete successfully, to tell coveralls that the coverage uploads are done.
I had to adjust goveralls to use the CircleCI workflow ID instead of (by default) the build number, so that the uploaded coverage files are grouped correctly.
[Coveralls + CircleCI + parallelization docs](https://docs.coveralls.io/parallel-build-webhook#circleci-setup)
[TAU-1223]: https://outreach-io.atlassian.net/browse/TAU-1223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(coveralls): add support for parallel coveralls uploads

- shell/ci/testing/coveralls.sh
This should fix the case when a service doesn't have any E2E tests (i.e., it shouldn't try to upload coverage to coveralls).
CC: @davefry-outreach 
N/A
> fix(coveralls): handle when there are no E2E tests

- shell/test.sh
- versions.yaml
[DTSS-1095](https://outreach-io.atlassian.net/browse/DTSS-1095)
Updates `test.sh` with an implicit ENV-var parameter called
`PACKAGE_TO_DEBUG`.  When this variable is specified, the `test.sh`
script will invoke Delve on that particular package's tests.
Due to technical limitations, we can only debug one package at a time.
There is no way to run the entire suite of tests under a debugger all at
once, because each pckage creates its own test binary.
> feat: DTSS-1095 Allow `test.sh` to run under Delve

- shell/ci/env/asdf.sh
Different bundler versions create different Gemfile.lock versions, messing things up. This solves that problem.
[XX-XX]
> fix: Use fixed bundler version (from flagship Gemfile.lock)

- shell/ci/auth/github.sh
- shell/gobin.sh
This PR stubs `~/.config/gh/hosts.yml` to enable tools that depend on the github CLI to authenticate in CI.
[DTSS-1186]
[DTSS-1186]: https://outreach-io.atlassian.net/browse/DTSS-1186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ci/auth/github): write out gh hosts.yml config

- shell/protoc.sh
this is important particularly when importing from a bootstrap repo. protobuf expects imports to match their generated files
Example:
settings has `table.proto` which it imports as `import table.proto`
settingsworkflow, uses `go-protoc-imports` to import from settings, but the default path required importing table as `import api/table.proto`, these changes allow us to specify that the protoc include path should be under `/api`. This allows the imports to match and the reflection servers to function properly (among avoid other possible mismatch bugs)
Heres what it looks like in a `service.yaml` file:
```
go-protoc-imports:
- module: "github.com/getoutreach/settings@latest"
path: "/api"
```
- this is a breaking change, however this key is currently only used by settings services all owned …
> feat: (protoc.sh) update go-protoc-import field to support setting the import path under the module

- root/Makefile
This fixes issues where `goreleaser` would sometimes respect a pre-release tag over the newer version based on git tag ordering. This allows us to set the actual version.
[DTSS-0]
[goreleaser code ref](https://github.com/goreleaser/goreleaser/blob/f01c60026ce6320447736a9e562af85bbf649562/internal/pipe/git/git.go#L228)
> fix(goreleaser): explictly pass version to goreleaser

- shell/deploy-to-dev.sh
Currently trying to deploy to devenv with latest results in the following error: 
```
/Users/mukund.kidambi/outreach/smartstorecdctestproducer/scripts/../.bootstrap/shell/deploy-to-dev.sh: line 56: ./build-jsonnet.sh: No such file or directory  app.name=smartstorecdctestproducer app.type=bootstrap
```
This is due to the use of a relative path in the script path.
[XX-XX]
> fix: Fixing relative path in build script

- shell/ci/testing/setup-devenv.sh
It looks like the `TEST_TAGS` got removed from the Makefile when the E2E rework was done. This was always an issue of misdirection anyways, so now we explicitly set it when we call the E2E runner.
[XX-XX]
> fix(e2e): set correct TEST_TAGS

- root/Makefile
In `devspace` the `apiKey` file is mounted and based on vault secret. There's no need to pull it from vault into a file.
[XX-XX]
> fix: Use honeycomb apiKey from secret mount if file exists

- shell/devspace_start.sh
We pass env variables to help startup script decide whether to start the terminal, or start the app.
These variables are passed from devenv https://github.com/getoutreach/devenv/pull/224
When it starts the app and source watchers, it sends the logs into a file - this file is tailed in container entrypoint. https://github.com/getoutreach/bootstrap/pull/1099
[DTSS-1520]
[DTSS-1520]: https://outreach-io.atlassian.net/browse/DTSS-1520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(devspace): Send logs to datadog

- shell/debug.sh
Enables debugging bins based on environment variable. This is passed through from `devenv`, and bootstrap adds it in `devspace.yaml` config.
Other PRs to make it work e2e:
- https://github.com/getoutreach/bootstrap/pull/1108
- https://github.com/getoutreach/devenv/pull/231
[DTSS-1466]
[DTSS-1466]: https://outreach-io.atlassian.net/browse/DTSS-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(devspace): Support debugging non-default binaries (e.g. cdc bins)

- shell/fmt.sh
This PR fixes the fmt script to skip the new snapshot directories but also refactors the invocations of commands to share ignored directories and be less complex to add.
[XX-XX]
> fix(shell/fmt): skip .snapshot directories

- orbs/shared/commands/setup_devenv.yaml
- orbs/shared/jobs/e2e.yaml
- shell/ci/testing/setup-devenv.sh
https://outreach-io.atlassian.net/browse/DTSS-1592
Made associated change in bootstrap to  kick a circle ci build for bulkworkflow -
https://github.com/getoutreach/bootstrap/pull/1150/files
The checks below are to see if it downloaded the pre-release/latest devenv version depending on the environment variable.
With pre-release devenv version - (ignore the fact that e2e test failed) https://app.circleci.com/pipelines/github/getoutreach/bulkworkflow/345/workflows/1b938040-f734-4f97-b239-ed9f5634bd47/jobs/1460
With latest devenv version - 
https://app.circleci.com/pipelines/github/getoutreach/bulkworkflow/346/workflows/631e8595-1456-4ef3-8a20-e8c6946651a3/jobs/1465
> feat: add the ability to run devenv pre-release version for circleCI e2e test

- e2e/e2e.go
`devenv deploy-app` is deprecated and need to use `devenv apps run`
https://outreach-io.atlassian.net/browse/DTSS-1594
> fix: Use apps deploy and not deploy-app

- root/Makefile
- shell/devconfig.sh
… today
We are going to use Telefork for getting CLI telemetry. For that we need the API key we now store in vault. The API key is public, included in our other clients already.
[DTSS-1629]
[DTSS-1629]: https://outreach-io.atlassian.net/browse/DTSS-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Added Telefork API key for CLI telemetry

- shell/ci/release/confluence-publish.sh
This PR ignores any chore commits when looking for changed markdown files. 
[[DTSS-1567]]
Current state: when confluence-publish runs, the actual commit could have one or more chore (bot) commits infront of it. I have found cases where the commit has  a sementic-release-bot in front of it, and a sementic-release-bot and dependabot commit in front. 
This change tries to be a little smarter about which commits we compare by looking at only the non-bot commits.
[DTSS-1567]: https://outreach-io.atlassian.net/browse/DTSS-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: confluence publish with chore commits

- shell/test.sh
This PR introduces both shuffle tests (if the go version supports it) and race condition check.
[DTSS-1369]
Bootstrap was not the culprit of the initial issue, but to ensure that no project becomes a victim of race condition errors, we decided to add the check to all tests.
To avoid breaking a lot of projects with the new `-race` flag, this PR allows disabling the check by adding `RACE: disabled` environment variable to the `test` job in `.circle-ci/config.yml`.
[DTSS-1369]: https://outreach-io.atlassian.net/browse/DTSS-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(test): shuffle and race tests

- root/Makefile
`jsonnet` should be run via gobin to ensure that it's installed/used by whatever version of Go that asdf currently has installed.
Also updated the version of `jsonnetfmt` to be consistent. Although at this point I'm not sure where that's used. `shell/fmt.sh` has its own definition:
https://github.com/getoutreach/devbase/blob/8f1d9c437371059f7f94f4904bc5253a6926c6aa/shell/fmt.sh#L15
I'd be happy to delete that line in `root/Makefile` if it's unused.
> fix(update-pipeline): use jsonnet from gobin

- README.md
- shell/golangci-lint.sh
* this is a fix that it seems has had some success from my tests. the
error will still occur the first time running in large repos such as
dsngsyncworkflow, but subsequent runs w/changed code seem to be fine.
[XX-XX]
> fix: too many open files for golangci-lint

- versions.yaml
Latest clerkgenproto has bootstrap-friendly protobuf aliases we need in ingest handler, bringing it into devbase (then bootstrap next).
[QSS-1043]
[QSS-1043]: https://outreach-io.atlassian.net/browse/QSS-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bump clerkgenproto to latest for new features

- shell/ci/release/confluence-publish.sh
This fixes confluence publish to handle an additional case where there is a commit after the current tag. Some publish jobs are failing due to this.
This handles all previous cases plus the case where there was a commit after the current tag.
[DTSS-1838]
[DTSS-1838]: https://outreach-io.atlassian.net/browse/DTSS-1838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: handle newer commits in confluence publish

- shell/asdf-exec.sh
- shell/go.sh
Adds an `asdf-exec.sh` script that will `asdf exec` the given arguments
in an environment that respects the embedding project's `.tool-versions`
file.
In a perfect world, this functionality would be baked in to `asdf`
upstream.  For now we build this functionality from hacky shell scripts.
It may break in some edge case scenarios, but it should be good enough
for all the situations we're likely to encounter int he real world.
Also adds a `go.sh` that does `asdf-exec.sh go`.  This is intended to
provide compatibility for tools require us to point at the "Go
executable".
> feat: Add 'asdf-exec.sh' and 'go.sh'

- versions.yaml
Updates clerkgen version to [v1.23.0](https://github.com/getoutreach/clerkgen/releases/tag/v1.23.0)
[DP-3591]
[DP-3591]: https://outreach-io.atlassian.net/browse/DP-3591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bumping clerkgen version

- shell/fmt.sh
- shell/golangci-lint.sh
- versions.yaml
* jsonnetfmt update fixes 1.18 errors because of an outdated x/sys package
* unforking and updating golangci-lint to get off of jareds branch - we did that initially because we couldn't update golangci-lint outside of a breaking change release. we're just gonna start updating this linter every breaking change release
[XX-XX]
> fix: update jsonnetfmt and golangci-lint

- orbs/shared/jobs/test_node_client.yaml
The  path generated by stencil-golang is different now.
[DTSS-2004]
[DTSS-2004]: https://outreach-io.atlassian.net/browse/DTSS-2004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Path to node grpc client tests

- go.mod
- shell/ci/testing/setup-devenv.sh
We recently did a v2 of devbase, so we need to update the `go.mod` and subsequent callers to reflect the new import path. This does that for `devbase`
[XX-XX]
> fix: update import path for v2

- e2e/e2e.go
This PR moves us from using `flagship` as the `outreach` dependency name to `outreach` to match our deployment name. We'll be able to remove the flagship dependency list once reactor is dead as well.
This is a BREAKING CHANGE because users will need to change their `flagship` dependency to `outreach.
A side change here is we now also read `VAULT_ADDR` from the box config. This may be slightly adjusted soon to allow setting a vault address just for CI
[DTSS-2007]
[DTSS-2007]: https://outreach-io.atlassian.net/browse/DTSS-2007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat!: flagship -> outreach, read vault addr from box config

- shell/ruby/publish.sh
We no longer push to package cloud for Ruby packages. This has been deprecated for over a year and currently has broken.
[XX-XX]
> fix(publish): only push to github package

- shell/protoc.sh
Protoc is currently creating wrong imports for grpc package:
```
-import * as grpc from "@grpc/grpc-js";
+import * as grpc from "grpc";
```
[RMS-743]
[RMS-743]: https://outreach-io.atlassian.net/browse/RMS-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: generate protobuf TS code for grpc properly

- orbs/shared/jobs/e2e.yaml
Enables the ability to specify the resource class for e2e test job
> feat: enable e2e job to have resource_class param

- shell/fmt.sh
[QSS-1192](https://outreach-io.atlassian.net/browse/QSS-1192)
Adds `.git` to the set of excluded paths for `make fmt`.
While working on QSS-1192, I encountered PR failures that should have
been fixable with `make fmt`.  When I ran `make fmt`, this happened:
```
$ make fmt
:: Running Formatters
-> goimports
./.git/logs/refs/heads/qss_1152_shipper_metrics.go:1:63: expected ';', found d2c8185d8f061a1c9bf6e2748ec6c4fbf33ca65a
./.git/logs/refs/heads/qss_1152_shipper_metrics.go:1:138: illegal character U+0040 '@'
./.git/logs/refs/heads/qss_1152_shipper_metrics.go:2:117: illegal character U+0040 '@'
./.git/logs/refs/heads/qss_1152_shipper_metrics.go:3:117: illegal character U+0040 '@'
./.git/logs/refs/heads/qss_1152_shipper_metrics.go:4:2: expected '}', found 'EOF'
```
That's concerning.  I …
> fix: QSS-1192 Do not `fmt` anything in `.git`

- shell/build-jsonnet.sh
Adds a region variable to be passed into the kubecfg command. 
The reason for this is that trying to reference `app.region` in an overrides jsonnet file is erroring on e2e tests in circleci.
[XX-XX]
> fix: add region to build-jsonnet kubecfg command

- shell/protoc.sh
[XX-XX]
* docker-protoc behavior can be seen here:
https://github.com/namely/docker-protoc/blob/master/all/entrypoint.sh#L149
https://github.com/namely/docker-protoc/blob/master/all/entrypoint.sh#L392
* original implementation of this script using
`--validator-source-relative`
https://github.com/getoutreach/devbase/blob/d925a545bf978ebb98174edb25d4828cac5c381c/shell/protoc.sh#L82
> fix: match source relative behavior from original docker-protoc impl

- shell/devspace_start.sh
Uses the correct bash flag to test for e2e tests.
[XX-XX]
> fix: correctly detect e2e tests in devspace

- e2e/e2e.go
**What this PR does / why we need it:**
make e2e is failing when there are files with only build tag or_int in the folder with err: "import: no buildable Go source files in ..."
JIRA ID: DT-00
[XX-XX]
> fix: be tolerant to file with not compatible build tags

- e2e/e2e.go
- go.mod
- go.sum
- shell/devconfig.sh
This PR fixes a few misc RMS team issues:
* Localizer wouldn't always be killed when `/var/run/localizer.sock` was left over from a previous process, this is now detected and cleaned up.
* `devconfig.sh` would sometimes output a false `jq` error, this was because `deploy-to-dev.sh` had more output added to it. Now we use the dedicated `build-jsonnet.sh` script instead which only returns the YAML.
[XX-XX]
> fix: misc RMS fixes, localizer cleanup, jq error

- orbs/shared/jobs/e2e.yaml
* adds a way to configure the no_output_timeout for the actual step
that runs e2e for the e2e job
[XX-XX]
> feat: configurable no output timeout for e2e job

- .tool-versions
- shell/golangci-lint.sh
- versions.yaml
This PR moves us to use asdf for `golangci-lint`, which is marginally helpful for Go upgrades (e.g. 1.19) as they tend to use newer Go versions then we do, which prevents us from upgrading across the board because gobin builds them with the host Go version.
[XX-XX]
> feat(golangci-lint): use asdf

- shell/ci/release/unstable-release.sh
This PR makes the behaviour in #298 slightly better by checking for a `.goreleaser.yml` in the repository directory to determine if we should use the `unstable` releasing behaviour, over just git references.
[XX-XX]
> fix(release/unstable): only release unstable on artifacts

- root/Magefile.go
This PR unbreaks `make build` on repositories with no artifacts, where CI will attempt to call `make build` (e.g. for custom `make build` additions)
[XX-XX]
> fix(build): skip gobuild when no cmd directory exists

- shell/lib/asdf.sh
When we first install `asdf`, we have no plugins, so... it errors when we try to list plugins. Nice.
[DT-2808]
[DT-2808]: https://outreach-io.atlassian.net/browse/DT-2808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(asdf): if plugins list fails, empty output

- shell/lib/asdf.sh
This pr fixes the asdf plugin list logic, plugin-add would be ran but the list wouldn't be updated, so the NOOP logic wouldn't trigger. Now, we regenerate after plugin-add
[DT-2808]
[DT-2808]: https://outreach-io.atlassian.net/browse/DT-2808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(asdf): regenerate plugins list caching on plugin-add

- shell/fmt.sh
- shell/lib/bootstrap.sh
Switches `bootstrap.sh` to use `arguments` prefix when looking up keys in `services.yaml`.
[XX-XX]
> fix: use stencil arguments for looking up keys

- shell/languages/nodejs.sh
If we change node versions for the client, this issue can happen. This ensure that we always have yarn before running it.
[DT-2927]
[DT-2927]: https://outreach-io.atlassian.net/browse/DT-2927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ensure yarn is present before running yarn install

- e2e/e2e.go
Seeing this error on every e2e test run: 
```
DONE 13 tests in 7.684s
12:39PM INF Killing the spawned localizer process (spawned by devenv tunnel)
12:39PM WRN failed to kill running localizer server error="rpc error: code = Canceled desc = context canceled"
```
It seems that we are using a context which is always going to be cancelled by this point.
This change creates a new context just for the kill operation.
[XX-XX]
> fix(localizer): don't use cancelled context

- shell/ci/testing/codecov/get-upload-token.sh
Was just exiting 0 and not actually returning (echoing) anything which i think resulted in https://app.circleci.com/pipelines/github/getoutreach/tollmon/658/workflows/fb299293-be7e-49ba-9f31-353a37ed2341/jobs/2593?invite=true#step-110-4
[XX-XX]
> fix: echo upload token if env var is set

- root/Makefile
- shell/golangci-lint.sh
This allows configuring the cache directory so that we can still use a cache while running an application in `devenv`.
[DT-2966]
[DT-2966]: https://outreach-io.atlassian.net/browse/DT-2966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: allow configuring lint cache directory

- .tool-versions
Backports ruby 2.7.5 to devbase `2.2.x`, which is the [version being used by bootstrap v10.2.x](https://github.com/getoutreach/bootstrap/blob/v10.2.2/versions.yaml#L21). 
For posterity, I created `release-2.2` by doing the following:
```bash
$ git checkout v2.2.1
$ git checkout -b release-2.2
```
```yaml
branches:
- name: release-2.2
range: 2.2.x
channel: ''
```
**Note**: `yarn run semantic-release` doesn't work until you push the branch up to the remote, sadly.
[XX-XX]
> fix(tool-versions): ruby 2.7.5

- versions.yaml
Picks up changes related to copyright statements & some other stuff for silver.
> fix: Update lintroller to the latest version.

- shell/lintroller.sh
set pipefail to break and exit when lintroller fails
**test repo:** https://github.com/getoutreach/rms/commit/9e61156cb77530334bec245fad575a6eaf361771
**before change**
rms % make lint
GOPROXY= GOPRIVATE=github.com/getoutreach/* OUTREACH_ACCOUNTS_BASE_URL=https://accounts.outreach-dev.com SKIP_VALIDATE= SKIP_LINTERS= OSS=false TEST_TAGS=or_test GOLANGCI_LINT_CACHE="/Users/cluangma/.outreach/.cache/.golangci-lint/rms" ./scripts/shell-wrapper.sh linters.sh
:: Running linters
-> shellcheck (.sh,.bash) (0.719s)
-> shellfmt (.sh,.bash) (0.597s)
-> go mod tidy (.go) (0.681s)
-> golangci-lint (.go) (5.119s)
-> lintroller (.go)
-: file "/Users/cluangma/github/rms/internal/validator/result.go" does not contain the required header key "Description" and corresponding value existing before the …
> fix: set pipefail for lintroller

- shell/linters/prettier.sh
- format and check lint .ts files
- change loglevel to log to print files that failed lint check
- break lint check if prettier fails
**test repo:** https://github.com/getoutreach/nirupamaintro/tree/4321fe9ac0adfb2aaa9e53e2c872d06066d37f8a
**before change**
nirupamaintro % make lint 
GOPROXY= GOPRIVATE=github.com/getoutreach/* OUTREACH_ACCOUNTS_BASE_URL=https://accounts.outreach-dev.com SKIP_VALIDATE= SKIP_LINTERS= OSS=false TEST_TAGS=or_test ./scripts/shell-wrapper.sh linters.sh
:: Running linters
-> shellcheck (.sh,.bash) (1.134s)
-> shellfmt (.sh,.bash) (0.990s)
-> go mod tidy (.go) (0.995s)
-> golangci-lint (.go)
-> golangci-lint (.go) (5.638s)
-> lintroller (.go) (1.412s)
-> eslint (.js) (0.74s)
-> prettier (.js) (0.79s)
-> prettier (.yaml,.yml,.json,.md,.ts) (2.573s)
-> buf (.proto) …
> fix: format and check lint for .ts files

- orbs/shared/jobs/save_cache.yaml
This runs the full cache generation only if there was a new commit since the last run.
The implementation is rather hackey, but CircleCI has no built in way to handle this kind of behavior.
[DT-3123]
[DT-3123]: https://outreach-io.atlassian.net/browse/DT-3123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(cache): conditionally run daily cache

- orbs/shared/executors/testbed-machine.yml
- shell/circleci/machine.sh
This PR updates the `testbed-machine` executor to use a new version of Ubuntu. This, hopefully, fixes issues in e2e tests like such:
```
Reading package lists... Done       
E: Repository 'https://cli-assets.heroku.com/apt ./ InRelease' changed its 'Origin' value from 'Heroku' to 'Jeff Dickey @jdxcode'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```
If the Heroku APT repository had a hostile takeover and the newer image still includes it, this will not fix the issue. Going to wait to merge until I validate that this does, in fact, fix the issue.
This PR also removes the `heroku.list` APT entry to remove issues with it.
[DT-0]
> fix(executor/testbed-machine): use newer ubuntu image + remove heroku APT

- shell/fmt.sh
- shell/lib/shell.sh
update run_command to return exit code back to caller. so that linter.sh (caller) can [print out a recommendation to users
](https://github.com/getoutreach/devbase/blob/main/shell/linters.sh#L76)
https://outreach-io.atlassian.net/browse/DT-3150
> fix: run_command to return exit code back to callers

- root/Makefile
Since we still embed honeycomb and telefork keys in the binaries, this ensure that we have the keys available when we run `make build`.
[DT-2717]
[DT-2717]: https://outreach-io.atlassian.net/browse/DT-2717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(gobuild): ensure we have secrets for build

- .circleci/config.yml
- root/Makefile
- shell/devspace_start.sh
Adds a command for running e2e tests inside a session of `devenv apps e2e`. This runs e2e tests without a linter which should help with general performance of e2e tests in devspace.
[DT-2967]
[DT-2967]: https://outreach-io.atlassian.net/browse/DT-2967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(make): add a test-e2e command

- shell/ci/release/docker.sh
One of the repos I maintain had its Docker image creation CI configuration refactored, but the manifest `deployments/docker.yaml` wasn't created. As a result, no new Docker images have been created since. However, my team wasn't notified of this because despite the "Build and Push Docker Image" job failing, it returned exit code 0, so it wasn't obvious that there was an issue until we dug into the CI logs.
The proposed fix checks for the existence of the manifest and exits early with a non-zero code if it's not there (with a link to the manifest instructions).
> fix(docker): fail if no manifest file exists in repo

- shell/protoc.sh
ensures that when tagging to a branch (such as for developing) that it is always up to date during generation
> fix: clone protoc import target everytime

- shell/lib/shell.sh
For some reason stdin can mutate what `get_cursor_pos` returns, so attempt to validate that. If it fails, return `0,0`. This results in mangled output, but really the user shouldn't be writing to their terminal as they are running something non-interactively so I'm OK with that.
[DT-3132]
[DT-3132]: https://outreach-io.atlassian.net/browse/DT-3132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(lib/shell): get_cursor_pos validates format better (DT-3132)

- docs/makefile.md
- e2e/e2e.go
- shell/ci/testing/setup-devenv.sh
* runs a script after the devenv has deployed in an e2e test run,
if it exists.
[XX-XX]
> feat: post e2e script

- .circleci/config.yml
- service.yaml
- stencil.lock
Skips e2e test since we don't have any, and skips docker since it will no longer work with the newest devbase.
[XX-XX]
> fix: skip docker and e2e ci steps

- shell/devconfig.sh
[DT-3372](https://outreach-io.atlassian.net/browse/DT-3372)
Fixes a bug in `devconfig.sh`'s invocation of `build-jsonnet.sh` so it
will render the jsonnets in `local_development` mode instead of
`development` mode.
As I understand it, `local_development` is the environment for
developing on the developer's "host" machine.  The `development`
environment is for deploying to the developer's local k8s instance (ie.
`bento1a`).  The `devconfig` script is only relevant for
`local_development`.
The `devconfig.sh` script made a clear attempt to set the environment to
`local_development`, but it did so via a now-incorrect environment
variable.  In practice, it was rendering jsonnets with an environmetn
value of `development`.
I believe this confusion has been around for roughly six months now.
See …
> fix: DT-3372 Make devconfig env `local_development`

- shell/protoc.sh
Remove the imports of an unsupported plugin from all generated proto files. We still need to keep the plugin because it's heavily used in Go.
We have proved out that removing this manually still keeps the clients working as expected.
[DT-3283]
[DT-3283]: https://outreach-io.atlassian.net/browse/DT-3283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove unsupported validate proto plugin

- shell/devconfig.sh
[QSS-1704](https://outreach-io.atlassian.net/browse/QSS-1704)
Update `devconfig.sh` to support the installation of local overrides for kubernetes secrets defined in deployment jsonnets.
While `devconfig.sh` has long supported local installation of secrets defined via the `VaultSecret` CRD, it hasn't supported plain old k8s secrets until now.
We do not expect this feature to be widely used.  In 99% of cases, a `VaultSecret` defined in the service's `service.yaml` is the right way to handle secrets.  However, there are rare use cases, like the one described in the attached ticket, where one might want to hard-code a secret in jsonnets and have `devconfig.sh` know how to install it in `$HOME/.outreach`.
[QSS-1704]: https://outreach-io.atlassian.net/browse/QSS-1704?atlOrigin=eyJpIjoiNWRkNTljNz …
> feat: QSS-1704 Support secrets in devconfig

- root/Magefile.go
This makes filenames consistent across builds.
This could be breaking for people filtering logs based on very specific stack traces. I think that's probably fine.
> feat: Add -trimpath to go builds.

- root/Magefile.go
- shell/ci/release/confluence-publish.sh
- shell/ci/release/docs.sh
There are times when a release fails and docs don't get published, and when a future release happens the older docs (since we compare current diff vs. previous diff) don't get updated. The preferred behavior is to publish all docs to confluence each release, and only update engdocs/godocs on semantic/tagged releases.
[DT-3205]
[DT-3205]: https://outreach-io.atlassian.net/browse/DT-3205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: publish all files every release

- shell/linters/bash.sh
- shell/linters/go.sh
- shell/linters/js.sh
There are instances when running `make test` where an error that is thrown but the terminal will not exit and instead continue. There is a weird issue where if the linter function contains multiple commands and one fails the exit code does not explicitly return an exit value `1`.  This is the work around we came up with for now until we can further figure out a better solution 
DT-3405
> fix: linter not exiting on error

- shell/devconfig.sh
[DTSS-1744](https://outreach-io.atlassian.net/browse/DTSS-1744)
Updates the environment override for the `build-jsonnet.sh` invocation
for fetching non-vault secrets to `DEVENV_DEPLOY_ENVIRONMENT`.  This
is analogous to the fix in [1].
The feature to render non-vault secrets in [2] just a few days after [1] 
was merged.  However, it seems we made the same mistake as had been
historically present in the config-rendering `build-jsonnet.sh`.  Oops.
[1] https://github.com/getoutreach/devbase/pull/411
[2] https://github.com/getoutreach/devbase/pull/416
> fix: DTSS-1744 Correct vault secret fetching env

- orbs/shared/executors/testbed-machine.yml
This doesn't really add anything for us right now because of our usage of buildx
> fix(ci): remove docker_layer_caching by default

- shell/circleci/machine.sh
This PR fixes the Hashicorp APT keyring to contain the older key that is still in use in their repositories.
[ICM-459]
[ICM-459]: https://outreach-io.atlassian.net/browse/ICM-459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ci): patch hashicorp APT keyring with older key

- .circleci/config.yml
- .tool-versions
- service.yaml
- stencil.lock
- yarn.lock
The `.tool-versions` is used to calculate all service's dependencies, so things getting the latest commit to stencil-golang won't fully remove `ruby` until this does as well. So, here we are.
[XX-XX]
> fix: upgrade stencil modules to remove ruby dep

- .gitignore
- e2e/e2e.go
- scripts/devbase.sh
- service.yaml
- shell/ci/release/confluence-publish.sh
- shell/lib/shell.sh
- stencil.lock
- templates/scripts/devbase.sh.tpl
This PR fixes the tests to not wipe contents out on failure to calculate cursor position, only when able to do so.
I also added support for running devbase on devbase to enable better testing of devbase changes.
[DT-3487]
[DT-3487]: https://outreach-io.atlassian.net/browse/DT-3487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(lint): properly calculate when to erase contents, run devbase locally

- docs/linters.md
- docs/makefile.md
- shell/fmt.sh
- shell/lib/shell.sh
- shell/linters.sh
- shell/linters/bash.sh
- shell/linters/go.sh
- shell/linters/js.sh
- shell/linters/jsonnet.sh
- shell/linters/prettier.sh
- shell/linters/protobuf.sh
This PR changes the file detection logic for `fmt` and `lint` targets to not error on deleted files. This also optimizes them to use the same function for getting files, minus go linters which require package paths, and thus aren't applicable.
This is done by using `git ls-file` with support for untracked files and filtering out deleted files. `find` could've been used, but running `git check-ignore` would've been required to be ran on each file and would be expensive. So, `git ls-files` is continued to be used in this nuanced way.
[DT-3548]
[DT-3548]: https://outreach-io.atlassian.net/browse/DT-3548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(lint/fmt): dont error on deleted files

- scripts/devbase.sh
- templates/scripts/devbase.sh.tpl
Fixes a small bug in the new `local` logic that was introduced, when downloading from Github we wouldn't remove that directory first.
[XX-XX]
> fix(shell-wrapper): remove libDir before populating

- shell/debug.sh
api-version=2 is required for goland and doesn't hurt vscode
> fix: use api-version=2 in debug.sh

- shell/ci/release/release.sh
we want to get notified if releases fails because of opslevel check
[XX-XX]
> fix: send notification if opslevel check fails

- e2e/config/config.go
- e2e/e2e.go
- orbs/shared/jobs/e2e.yaml
- Currently before running e2e tests, both optional and mandatory dependencies were deployed to the cluster
- This change is about to deploy only optional dependencies of application under test, not optional dependencies of its dependencies
[QF-847]
[QF-847]: https://outreach-io.atlassian.net/browse/QF-847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: don't deploy optional transitive dependencies to speed up e2e tests

- e2e/e2e.go
- Docker build takes e.g. in `rms` 6 minutes which were previously added to `make e2e` execution time
- This change is about not building docker in the critical path, but together with app dependencies deployment where CPU load is low
[QF-848]
[QF-848]: https://outreach-io.atlassian.net/browse/QF-848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: build docker early to speedup e2e

- shell/grpcui.sh
Provide better error message to users when they run `make grpcui`. The rendered output message will look like:
```
this expects your service to either be running locally or have port forward running.
to port forward:
- deploy to devenv (i.e. "devenv app deploy .")
- run "kubectl port-forward service/[SERVICE-NAME] 5000:5000 -n [NAMESPACE]"'
```
DT-3582
> fix: add error message when `make grpcui` fails

- e2e/e2e.go
- shell/ci/testing/setup-devenv.sh
- Allow opt-out from running devconfig in parallel with apps deploy (introduced in https://github.com/getoutreach/devbase/pull/499)
- Based on feedback from copilot project, which has devconfig override that required application to be deployed prior to running it https://github.com/getoutreach/copilot/blob/main/scripts/devconfig.override.sh
- Opt out is based on REQUIRE_DEVCONFIG_AFTER_DEPLOY env var, which can be set on project level in CircleCI 
[XX-XX]
> fix: opt-out devconfig early

- orbs/shared/jobs/test.yaml
Adding no_output_timeout arg to test as well (e2e already had it). Matching CI fix is here: https://github.com/getoutreach/stencil-circleci/pull/107
[CDT-00]
> fix: add no_output_timeout to test

- .circleci/config.yml
- orbs/shared/jobs/save_cache.yaml
- orbs/shared/jobs/test.yaml
- shell/circleci/setup.sh
Users would like the ability to add packages or even run a script before running unit tests. This PR will allow users to specify a path that contains a shell script to run before test.
Tested successfully with this [CircleCI pipeline](https://app.circleci.com/pipelines/github/getoutreach/devbase/2701/workflows/a19e9c98-9ae5-44de-b050-acbca4f1d6c4/jobs/6509)
DT-3641
> feat:  pre-setup-script for tests

- shell/opslevel/upload_prismaci.sh
Looks like the prisma script is reading from the wrong file when determining if the artifact exists.
[XX-XX]
> fix: upload_prismaci.sh to use SCAN_RESULTS_FILE

- root/Makefile
- shell/fly.sh
This allows `make update-pipeline` to be run on non-macOS systems.
[DT-3750]
[DT-3750]: https://outreach-io.atlassian.net/browse/DT-3750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(fly): do not run brew on Linux/WSL

- shell/ci/testing/setup-devenv.sh
It looks like they changed their GPG key path and then rotated their keys and didn't update the old path (but still serve it). So, we're using the new path. Updated to their new instructions, including a new path to download it to. Love it.
[XX-XX]
> fix(setup-devenv): use new gcp kubectl key

- orbs/shared/jobs/save_cache.yaml
- orbs/shared/jobs/test.yaml
Fixes the `pre_setup_script` argument to not be required. As per the
[CircleCI documentation](https://circleci.com/docs/reusing-config/#parameter-syntax:~:text=N/A-,default,-The%20default%20value) an argument is required if there is not
'default' key set.
> fix(orb/job/test): dont require pre_setup_script

- shell/ci/testing/setup-devenv.sh
When operating on a file, `gpg --dearmor` will write the output to
another file on disk. However, if you pipe the file it will write to
stdout. I tested this while piping, so this broke once I released it.
Instead we now tell gpg to always output to stdout using `--output -`.
I've tested the entire function in CI now, so I'm confident this works.
> fix(e2e): use correct gpg dearmor command

- shell/debug.sh
Allow users to kill make debug with ctrl from inside the devenv
[DT-3698](https://outreach-io.atlassian.net/browse/DT-3698)
[DT-3698]: https://outreach-io.atlassian.net/browse/DT-3698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: allow ctrl-c to kill headless delve in make debug

- shell/lib/asdf.sh
This PR enables the repository's `.tool-versions` to override any version used by `devbase`, if set.
[DT-3749]
[DT-3749]: https://outreach-io.atlassian.net/browse/DT-3749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(asdf): allow overriding devbase tool-versions

- shell/ci/release/docker.sh
This changes how we parse the docker.yaml file to output each secret on a separate line instead of outputting a JSON array.
[DT-3807]
[DT-3807]: https://outreach-io.atlassian.net/browse/DT-3807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: parsing yaml arrays in docker.sh

- shell/debug.sh
This changes the behavior of to prioritize `PACKAGE_TO_DEBUG` environmental variable if it's set, and otherwise sets the `PACKAGE_TO_DEBUG` to `DEV_CONTAINER_EXECUTABLE` which is the environmental variable that we're adding with devspace profiles. 
I'm not tied to the if statement here, and if someone else has opinions I'd be fine changing it.
[DT-3757]
[DT-3757]: https://outreach-io.atlassian.net/browse/DT-3757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(debug): correct environmental variable that make debug evaluates

- root/Magefile.go
- shell/ci/release/docker.sh
- shell/ci/release/docker_test.sh
- shell/ci/release/testdata/test.yaml
- shell/lib/yaml.sh
- shell/lib/yaml_test.sh
Fixes the new `docker.sh` logic to properly support string values again.
Adds a test for the `get_image_field` function and changes `docker.sh`
to support being tested (albeit a little hackily).
Adds a `yaml_get_field` function that strips `null` for an empty string
to be easier to work with in Bash. Adds tests for the new
`yaml_get_field` function and behaviour.
[DT-3821]
[DT-3821]: https://outreach-io.atlassian.net/browse/DT-3821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(docker): properly handle string values again

- shell/lib/shell.sh
There is some logic in shell.sh's run_command function to put the terminal back one line. However, this is currently overwriting parts of error messages.
This changes the code so that the cursor is only moved back if the previous command ran successfully.
[DT-3800]
[DT-3800]: https://outreach-io.atlassian.net/browse/DT-3800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: don't overwrite prev line if error

- e2e/e2e.go
* fixes a race condition that puts my terminal into raw mode basically
because two different unsynchronoized processes are writing to stdout
at the same time? I don't know. It's my best guess. All I know is that
removing this from running in the background OR not outputting to
stdout fixes the problem.
[XX-XX]
Example of what happens (This is consistent 100% of the time) when this runs in the background the way it has been the past month or two: https://cl.outreach.io/RBuJ9PRo
> fix: devconfig stdout race condition

- shell/shellcheck.sh
The shellcheck wrapper uses asdf, not gobin.
> docs(shellcheck): clarify wrapper comments

- shell/lib/asdf.sh
Only reshim if we installed new tools. This saves 10+ seconds when you have a lot of tool versions installed.
Only run `awk` once, instead of two times per tool. This saves another 100ms or so.
---
`make` startup is ridiculously slow. This helps a lot with that.
> fix: Performance improvements for asdf.sh.

- root/Makefile
- shell/ci/env/asdf.sh
- shell/lib/asdf.sh
This is used only in linter scripts, which are run via `make`, which already invokes asdf_devbase_ensure.
Remove deprecated function call.
---
`make lint` invokes this ensure function an extra three times, which adds a surprising amount of time.
> fix: asdf_devbase_exec no longer ensures install.

- root/Makefile
- shell/ci/release/docker.sh
We already support building docker images defined in `docker.yaml` file, this change reuse the script to allow `devenv deploy` do the same behavior.
[DT-3624]
I ran local tests for some images, and it does not seem to be a breaking change. I could not run full testing for the `ds-mlp-website` repo, because I could not build the `co-service` successfully. I assume my aws access is not permitted to pull the specific S3 bucket.
[DT-3624]: https://outreach-io.atlassian.net/browse/DT-3624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: use ci docker build script to build docker images

- shell/vscode/golang-linters.sh
VSCode wasn't showing `lintroller` warnings because the `golangs-linter.sh` script was passing through `golangci-lint` flags to `lintroller`, even though they are not valid for it:
```
-: package run is not in GOROOT (~/.asdf/installs/golang/1.19.8/go/src/run)
-: malformed import path "--print-issued-lines=false": leading dash
-: malformed import path "--out-format=colored-line-number": leading dash
-: malformed import path "--issues-exit-code=0": leading dash
lintroller: 4 errors during loading
```
Instead we just have lintroller run for the entire service. (It appears that VSCode does not send package names to the golangci-lint script...)
[DT-3864]
[DT-3864]: https://outreach-io.atlassian.net/browse/DT-3864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …
> fix(vscode): don't pass golangci-lint flags to lintroller (DT-3864)

- docs/makefile.md
- e2e/e2e.go
- orbs/shared/jobs/e2e.yaml
Allow shared/e2e jobs to specify what snapshot target to use, either "base" or "flagship". This change helps to support new snapshot targets in the future.
[QF-910]
[QF-910]: https://outreach-io.atlassian.net/browse/QF-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Allow to specify provision target for shared/e2e step

- shell/ci/release/docker.sh
When we moved to using `ci/release/docker.sh` for docker builds,
that somehow caused `make version` to start printing
"entering directory" from `make`. So, we pass `--no-print-directory`
to prevent that message, since we don't want or need that.
> fix(docker): don't print directory when running make version

- shell/linters/kubecfg.sh
Adds a `kubecfg` linter that renders development manifests and ensures
they pass [`kubeconform`](https://github.com/yannh/kubeconform).
This doesn't get perfect coverage, since it doesn't generate them for
production (and all other possible cominations), but this should get us
a lot more coverage than what we had before (nothing).
Alternatively, we could try to generate it for all bentos using
Discovery, but given this repository is open-source -- that's a lot
harder to implement at the moment.
Success Case:
```bash
-> kubecfg (.jsonnet) (3.976s)
```
Error Case (bad env var value):
```bash
stdin - Deployment discovery is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec/template/spec/containers/0/env/1/value' does not validate with …
```
> feat(linters): add kubecfg validation

- orbs/shared/jobs/test.yaml
Adds the ability to pass `setup_remote_docker` to the `shared/test` orb.
This enables accessing Docker in tests. Defaults to `false`.
> feat(test): support setup_remote_docker in tests

- shell/ci/release/release.sh
This change prevents a publishing node clients if the repo is not a service and therefore will not have any clients to publish.
[DT-3704]
[DT-3704]: https://outreach-io.atlassian.net/browse/DT-3704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: only publish node client if releasing a service

- orbs/shared/commands/use_docker.yml
- shell/test.sh
- versions.yaml
Changed `test.sh` to fully document all environment variables in use.
Changed `_FLAG` and `_TAG` environment variables to use bash arrays to
ensure consistent space handling behaviour, while keeping space
splitting for pre-specified environment variables for compatability.
When passing `-v` to `TEST_FLAGS` (and in turn to `go test`) we now set
the `gotestsum` output format to be `standard-verbose` which is
equivalent to `go test -v`[1] output. Before, this was silently ignored
and frustrating to work with.
Updated the `shared/setup_docker` step to use a newer version of Docker
as the older version had issues with apt package installs (somehow?)
[1]: https://github.com/gotestyourself/gotestsum#:~:text=standard%2Dverbose%20%2D%20the%20standard%20go%20test%20%2Dv%20format.
> feat: rewrite test.sh to be better documented and use bash arrays

- shell/ci/release/docker.sh
- shell/lib/buildx.sh
As a follow up to #605, this updates the docker.sh output to better
reflect what the docker build is doing.
I also took the time to combine the logic for the docker build _test_
logic and the docker build _release_ logic (determined by the presence
of `CIRCLE_TAG`. This brings the added benefit of us building a docker
image on all archs that we would release to on PRs.
Updated buildx to reflect what is in use on most user's machines.
> fix: update docker.sh statement, deduplicate logic

- .tool-versions
- .vscode/launch.json
- go.mod
- go.sum
- stencil.lock
Upgrades Go to 1.19.11 through `stencil`. Also includes a `gobox`
upgrade.
> fix: Upgrade Go 1.19.11

- shell/fmt.sh
adds per-project formatters, just like linters
> fix: add missing per-project formatter for migrations

- shell/ci/release/confluence-publish.sh
Avoids redirecting `stdout` of `visualizemd` to create the markdown file, and instead uses the existing `-o` flag.
[DT-3756]
[DT-3756]: https://outreach-io.atlassian.net/browse/DT-3756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(confluence): don't append logs to markdown output

- shell/linters/kubecfg.sh
This fixes the case where the kubecfg linter is run in a Stencil repo that isn't a service but has jsonnet files for whatever reason.
> fix(linters): skip kubecfg linter if app jsonnet doesn't exist

- .tool-versions
- scripts/golangci.yml
Upgrades `golangci-lint` to `1.53.3` to support Go 1.20.
This likely brings in some new lint rules that _may_ fail on new
projects. Putting it in unstable to give us sometime to run into them
and adjust our rules as needed.
I didn't hit any in a few repos I tried this on.
> feat(golangci-lint): Upgrade to 1.53.3

- docs/makefile.md
- shell/test.sh
Adds the option to remove the `-shuffle=on` flag.  The use of `-shuffle`
disables test caching, which is not a great experience for TDD.  Many
devs will want to turn this off during local development.
> feat: Add `SHUFFLE=disabled` test env option

- .tool-versions
- root/Makefile
- shell/golangci-lint.sh
- shell/lib/asdf.sh
- shell/linters.sh
Upgrades golangci-lint to v1.54.1 to support Go 1.21. Adds a small
framework in `golangci-lint.sh` to explode if versions of Go and
golangci-lint are not compatible. Adds checks just for 1.21 and 1.20.
This is important because, most notably for 1.20, it can explode in CI
by consuming all the RAM and not be clear why that is happening.
Changes `GOGC` to no longer be set in favor of using total memory
calculation to pass to `GOMEMLIMIT`. Fallsback to `GOGC` if required.
It's important to note that this doesn't disable GC, just makes it less
important until we get close to total memory (or are otherwise unable to
free any).
Also updated `linter.sh`'s error to not blindly suggest `make fmt`.
Instead, it recommends it based on the output.
> fix(golangci-lint): upgrade to v1.54.1, fail on invalid version pairs

- orbs/shared/jobs/save_cache.yaml
Right now, `test` supports `setup_remote_docker` but `save_cache` does
not. This leads to potential issues with tests that need a remote docker
daemon to be available for their tests (thus failing to run on
`save_cache` but _not_ the `test` job).
This, fixes that, by supporting it in `save_cache` as well.
> fix(orbs/save_cache): support setup_remote_docker

- root/Makefile
`--rm-dist` has been deprecated with `--clean` replacing it[1], this PR
adjusts our usage to use `--clean` instead.
[1]: https://goreleaser.com/deprecations/#-rm-dist
> fix(goreleaser): switch from --rm-dist to --clean

- versions.yaml
Upgrades `lintroller` to 1.17 to (hopefully) fix some issues with it on
Go 1.20.
> fix(lintroller): upgrade to 1.17

- shell/ci/release/release.sh
Right now, due to our release process, we need to open PRs to merge
commits back into the correct branches. Because of this, sometimes a
closed PR will refuse to release.
To prevent this from happening, we remove those environment variables.
This fixes the current issue, I'll have a PR to refactor the existing
logic for this out soon.
> fix(release): always ensure PR metadata is omitted

- shell/ci/testing/setup-devenv.sh
Previous change forgot to add an import for `github.sh` (which provides
`install_latest_github_release`). This adds it.
Wish that Bash had an easier way to catch this statically...
> fix(setup-devenv): missing library import

- shell/lib/github.sh
- shell/lib/github_test.bats
While it's not the most performant for us to load dependencies on every
load of the library (since shell functions aren't namespaced), it's more
complicated/problematic to try to make consuming shell scripts aware of
the libary's dependencies. So, we have `lib/github` now import it's own
dependencies.
This could cause some issues with libraries that do initial state
setting (e.g., `asdf`) but most of those libraries should be designed to
only initialize their state once (which `asdf`, the example, does for
this reason)
> fix(lib/github): import required dependencies on load

- shell/ci/testing/delibird.sh
There were a few missing imports/env vars in the script. This fixes
them.
> fix(delibird): missing source/env vars

- root/Makefile
- fixes error when glibc version on CircleCI VM (ubuntu latest) does not match with glibc in dev-slim container
- fix is based on disabling [CGO](https://pkg.go.dev/cmd/cgo#:~:text=You%20can%20override%20the%20default,cgo%22%20if%20cgo%20is%20enabled.) which should help with cross-compiling that we do in binary sync (build on macos or ubuntu latest in CircleCI, run in dev-slim container on debian bullseye)
- verified [here](https://app.circleci.com/pipelines/github/getoutreach/devenvtestapp/118/workflows/1ef682dd-04a3-4cd9-aeba-2cc70cb03ea5/jobs/319) that it works
[QF-936]
[QF-936]: https://outreach-io.atlassian.net/browse/QF-936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: make devspace glibc error

- shell/ci/env/asdf.sh
Defaults to using the version of `npm` that is present with the
installed version of `node`. This prevents issues where the `npm` latest
version requires a version of node that is not in use, and in turn,
explodes the asdf node default npm packages install step silently.
> fix(asdf/node): dont install npm again

- orbs/shared/commands/with_node_client_cache.yml
This should fix the issue where the Node.js gRPC client uses a different version of Node.js from the tooling in the root directory, and thus doesn't get installed and fails during the `test_node_client` job.
Also changes references from `node` to `Node.js` where appropriate, to be clearer.
This will need to be hotfixed.
> fix(orb): ensure proper Node.js version is installed for its gRPC client

- CONTRIBUTING.md
Needed if you want to test orb changes.
> docs(contributing): add section on orb dev

- orbs/shared/commands/with_node_client_cache.yml
Rebuilding the CI cache via the [`rebuild_cache` parameter](https://github.com/getoutreach/devbase/blob/e253dce5053f7d33f8e1a98adc23d4fc1b9aae17/.circleci/config.yml#L8-L11) is sufficient to fix the bug described in #650.
> fix(orb): revert unnecessary asdf install step

- shell/lib/github.sh
Given we're downloading the tar file using the `repoName`, we should be
using that for the tar extraction as well. This changes the tar extract
command to do just that.
No test for this because we don't have any public repositories with
multiple CLIs in them :(
> fix(lib/github): extract tar file using repoName

- docs/linters.md
- docs/releasing.md
- scripts/unstable-release.include.sh
- scripts/update-toc.sh
- shell/ci/release/release.sh
- shell/ci/release/unstable-release.sh
Adds support for a shell script to be ran post-gh release creation of an
unstable release. Adds more comments/restructures some of the
unstable-release code to use the `yaml` library and be easier to read.
If `.goreleaser.yml` does not exist, the include script is still able to
be called to enable custom releasing functionality in that case.
Added a `unstable-release.include.sh` script for `devbase` to enable
publishing an orb on every unstable release of devbase.
Added documentation for unstable releases and the new include script
functionality.
> feat: support custom unstable-release post-release steps

- manifest.yaml
- shell/protoc.sh
- versions.yaml
Adds two new `service.yaml` driven `grpcOptions` fields:
* `disableDocGeneration` - Disables protobuf documentation generation.
* `latestGoProtobufModules` - Uses the latest Go protobuf modules.
Ideally each of these will become the default option later on, but for
now these must be manually enabled.
> feat: add configurable grpcOptions

- shell/ci/auth/github_packages.sh
- shell/ci/auth/packagecloud.sh
- shell/circleci/setup.sh
Updates `@getoutreach` scope to always use Github Packages. This is set
globally as our templates rely on Outreach packages. Users that wish to
have their own custom scopes should use a per-repo `.npmrc` instead.
Removes `packagecloud` since it hasn't been supported for a long time
(it also doesn't do anything).
[DT-4053]
[DT-4053]: https://outreach-io.atlassian.net/browse/DT-4053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: support @getoutreach npm packages

- shell/golangci-lint.sh
This change fixes how the the `golangci-lint` tool version is detected,
where a `v` prefix (e.g. `v1.XX.YY`) is not removed, causing incorrect
comparisons. The basic error is reproducible via the following short
script:
```bash
GO_MINOR_VERSION="1.20";
GOLANGCILINT_VERSION="v1.54.2";
GO_MINOR_VERSION_INT=${GO_MINOR_VERSION//./};
GOLANGCI_LINT_VERSION_INT=${GOLANGCILINT_VERSION//./};
if [[ $GO_MINOR_VERSION_INT == 120 ]] && [[ $GOLANGCI_LINT_VERSION_INT -lt 1520 ]]; then
echo "The mistaken assumption: $GOLANGCI_LINT_VERSION_INT -lt 1520";
fi
```
To fix, this introduces a second string manipulation where the character
`v` is removed from the `GOLANGCI_LINT_VERSION_INT`.
There is no JIRA for this, just fixing a bug as I found it.
> fix: Broken golangci-lint version detection

- .circleci/config.yml
- .editorconfig
- .github/CODEOWNERS
- .github/dependabot.yml
- .github/pull_request_template.md
- .gitignore
- .releaserc.yaml
- .tool-versions
- .vscode/launch.json
- package.json
- stencil.lock
- yarn.lock
Re-runs stencil and updates the npm dependencies. This is to test if the
newer semantic-release versions work so we can upgrade them globally.
Also moves to use the `@getoutreach`-scoped
semantic-release-circleci-orb package.
> fix: re-run stencil and update deps

- versions.yaml
Got the error when launching the debugger
```
Version of Delve is too old for Go version 1.21.3 (maximum supported version 1.20, suppress this error with --check-go-version=false)
```
We need to upgrade delve https://github.com/go-delve/delve/blob/master/CHANGELOG.md#1210-2023-06-23
[XX-XX]
> fix: Upgrade delve to 1.21 to support Go 1.21

- Makefile
This allows orb feature work to not clobber orbs published by the default branch.
> fix(orb): allow custom dev tags for publishing

- shell/ci/release/docker.sh
Docker cache keeps increasing with each build and will reset itself once it hits 15G in circleci, this will prune cache after each build and will keep usage under 6GB. 
Another solution could be to switch to different provider, rather then DLC in circleci. For example https://docs.docker.com/build/cache/backends/s3/
[XX-XX]
> feat: Tweak cache

- orbs/shared/jobs/save_cache.yaml
Despite having the job parameter for it, it wasn't actually being used by the job.
> fix(orb): use pre_setup_script in save_cache job

- orbs/shared/executors/testbed-machine.yml
Updates to the newest snapshot of the `ubuntu22.04` image.
> fix(orbs/shared): update machine executor image

- shell/linters/prettier.sh
Fixes the following warning when running `make lint` / `make fmt`:
```
[warn] Ignored unknown option --loglevel=log. Did you mean --log-level?
```
> fix(prettier): use the correct log level flag

- shell/ci/testing/delibird.sh
- shell/lib/asdf.sh
- shell/lib/shell.sh
the `asdf` utilities file uses `readarray`, which is not implemented in the version of bash that comes with macOS (which is 3.2). So, check the bash version array's major version at the beginning of the file.
Tested on macOS (thanks @jaredallard) and Linux with both Bash 3.2 and Bash 5.x.
[DT-4123]
[DT-4123]: https://outreach-io.atlassian.net/browse/DT-4123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ensure asdf utilities are run with bash 5 or greater

- shell/lib/asdf.sh
Promote rc to stable, created by `dt release promote`
> chore: Promote rc to stable

- root/Makefile
> fix(makefile): adjust shell quoting for cgo-enabled script

- shell/lib/box.sh
- shell/lib/box_test.bats
In addition to what it says on the tin, the PR fixes the following:
* Delete the generated temporary directory instead of the entire system `TMPDIR` on `EXIT` signal captured
* Put `yq` flag in the correct position
[DT-4111]
[DT-4111]: https://outreach-io.atlassian.net/browse/DT-4111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(box): abort early if the box repo can't be cloned correctly

- root/Makefile
This is for consistency with the other commands which utilize `CGO_ENABLED`.
> fix: use CGO_ENABLED for make gobuild

- orbs/shared/jobs/test.yaml
Unfortunately, I have a test that takes longer than 10 minutes and this isn't currently configurable.
The test.sh looks for this env var and sets the timeout flag:
https://github.com/getoutreach/devbase/blob/be1b62d86f8295ea542f9adecdf7ace7990cf5bc/shell/test.sh#L103-L106
[XX-XX]
> feat: make go test timeout configurable in test job

- root/Magefile.go
- root/Makefile
When we build the binary with `make devspace`, the debug information is not there and we cannot see the variable value in VSCode debugger. The PR is to address it.
Before the change:
After the change:
[XX-XX]
> feat: Add gcflags to devspace for Go services

- shell/ci/testing/coverbot/upload-coverage.sh
The default AWS account ID was added in [`gobox@v1.86.0`](https://github.com/getoutreach/gobox/releases/tag/v1.86.0).
> fix(coverbot): remove hardcoded AWS account ID

- shell/ci/testing/setup-devenv.sh
e2e tests are failing because of that:
https://outreach-hq.slack.com/archives/CN9MU7GLW/p1709544566147719
https://app.circleci.com/pipelines/github/getoutreach/gearbox/7432/workflows/c962a003-0ed0-4f3f-9d26-ec9dcb19cdfc/jobs/50980
the URL is from: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management
[XX-XX]
> fix: use new apt source for kubectl

- shell/yq.sh
- templates/scripts/devbase.sh.tpl
- templates/scripts/versions.yaml
As it turns out, trying to use the symlink didn't work when running stencil on a different repository, but with the unstable version of devbase (it somehow worked when running stencil on devbase, which is confusing). Trying to fix stencil itself so it can work with symlinks which reference things outside of the template directory just seems like a security vulnerability waiting to happen, so I've opted to just have the duplicated version inside of the template.
Also added a comment in `shell/yq.sh` to give context as to why it doesn't use `get_tool_version` to read the gojq version from `versions.yaml`.
> fix(yq): hardcode gojq version in scripts/devbase.sh

- scripts/devbase.sh
- templates/scripts/devbase.sh.tpl
This fixes the bug where docker images on arm64 couldn't be created.
CC: @nissim-natanov-outreach
> fix(gojq): normalize arm64 arch name

- orbs/shared/jobs/release.yaml
Adds a `no_output_timeout` param that maps to `no_output_timeout` on the release, with a default of `10m`. [Related issue](https://outreach-hq.slack.com/archives/CN9MU7GLW/p1705408681156669)
[DT-4165]
[DT-4165]: https://outreach-io.atlassian.net/browse/DT-4165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add `no_output_timeout` param

- versions.yaml
Got the error when launching the debugger
```
Version of Delve is too old for Go version go1.22.0 (maximum supported version 1.21, suppress this error with --check-go-version=false)
```
We need to upgrade delve https://github.com/go-delve/delve/blob/master/CHANGELOG.md#1220-2023-12-29
[XX-XX]
> fix: Upgrade delve to 1.22 to support Go 1.22

- shell/gobin.sh
See https://github.com/getoutreach/gobin/pull/145 for details.
[DT-4309]
[DT-4309]: https://outreach-io.atlassian.net/browse/DT-4309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: upgrade gobin to 1.11.5 to fix `go mod tidy` issues

- scripts/devbase.sh
- templates/scripts/devbase.sh.tpl
There is a use case where `make gogenerate` (and thus, `scripts/devbase.sh`) are run in an Alpine Linux Docker container. In that case, `curl` doesn't exist by default, but `busybox` does, which has a `wget` applet. If `busybox` is detected, prefer using that over `curl`.
Also add support for GNU `wget` since it's effectively the same command as the busybox one.
> fix(gojq): allow fetching via busybox or wget

- Makefile
- shell/catalog-sync.sh
Does what it says on the tin. This script only updates some basic fields, it's not exhaustive. An exhaustive updater would effectively require a Go-based script. It currently only supports Cortex but can be extended to other service catalogs' manifests.
[DT-4324]
[DT-4324]: https://outreach-io.atlassian.net/browse/DT-4324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add catalog sync script, used when catalog manifest isn't a template

- go.mod
- go.sum
- root/go.go
This resolves the Dependabot alert for https://github.com/advisories/GHSA-3f2q-6294-fmq5
> fix: replace vulnerable, unmaintained dependency with a fixed, maintained fork

- root/go.go
Fixes the case where HTTPS URLs sometimes weren't being parsed correctly.
[DT-4333]
[DT-4333]: https://outreach-io.atlassian.net/browse/DT-4333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(go): parse HTTPS git URLs correctly

- shell/linters/prettier.sh
Allows support for both the Prettier 2 and Prettier 3+ variants of the log level flag.
> fix(linters): pretter 3+ log level flag compatibility

- shell/ci/release/pre-release.sh
This PR fixes the case when a repo does not set up goreleaser. It should run RC release check first if applicable. 
Example: https://app.circleci.com/pipelines/github/getoutreach/stencil-circleci/1018/workflows/6da65a0e-50f5-4977-b766-11b8486e4f84/jobs/1856
[XX-XX]
> fix: rc prerelease before unstable release

- shell/ci/testing/delibird.sh
There hasn't been any new development on the `delibird` client in a while, so it should be safe to assume that we can use the stable version instead of the unstable version.
> fix(delibird): use stable version of delibird

- Makefile
For some reason the `sed` platform-specific conditional wasn't working correctly in macOS. So replace it with a cross-platform `perl` command. We expect that `perl` is installed by default on any machine that runs `stencil` for this repository.
> fix: replace awkward sed command with less awkward perl command

- Makefile
> chore: remove duplicate Makefile var

- orbs/shared/commands/use_docker.yml
Docker 20 is deprecated.
[DT-4396]
[DT-4396]: https://outreach-io.atlassian.net/browse/DT-4396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ci): use Docker 24 for remote docker images

- shell/catalog-sync.sh
Also only updates the Go version if there's a Go version in `.tool-versions`.
> fix(catalog-sync): ensure that the lintroller and reportingTeam fields exist in service.yaml

- shell/linters/prettier.sh
Using `--check` instead of `--list-different` should make it clearer to folks who don't use `prettier` by default what the problem is and how to solve it.
[DT-4452]
[DT-4452]: https://outreach-io.atlassian.net/browse/DT-4452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(prettier): better messaging when it fails

- shell/ci/auth/aws-ecr.sh
- shell/circleci/setup.sh
Make it more obvious in the CI logs that we're logging into AWS ECR.
Also add support for `foo.amazonaws.com/bar` registries.
[DT-4464]
This is what it looks like in the terminal:
```shell
❯ DOCKER_PUSH_REGISTRIES=accountid.dkr.ecr.region.amazonaws.com/somepath shell/ci/auth/aws-ecr.sh 
-> Authenticating with AWS ECR in accountid.dkr.ecr.region.amazonaws.com/somepath
WARNING! Your password will be stored unencrypted in $HOME/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credential-stores
Login Succeeded
```
[DT-4464]: https://outreach-io.atlassian.net/browse/DT-4464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(circleci): better logging, better ECR compatibility

- shell/circleci/setup.sh
* Don't override the env var
* Possible subtle bash bug by using `source` vs. calling the script directly
[DT-4464]
[DT-4464]: https://outreach-io.atlassian.net/browse/DT-4464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(circleci): only set DOCKER_PUSH_REGISTRIES from box if it's unset

- shell/circleci/machine.sh
This installs the AWS CLI in environments where it's needed for ECR authentication, namely building and publishing containers.
[DT-4464]
[DT-4464]: https://outreach-io.atlassian.net/browse/DT-4464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ci): install awscli

- shell/docker-build.sh
This should fix the tagging issues when running `make e2e`.
[DT-4504]
[DT-4504]: https://outreach-io.atlassian.net/browse/DT-4504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(docker-build): use get_box_array to fetch push registries from box

- shell/docker-build.sh
- shell/lib/docker.sh
Add functions into the docker library file.
Also refactors naming to be consistent in the docker library file.
[DT-4464]
[DT-4464]: https://outreach-io.atlassian.net/browse/DT-4464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(docker): standardize fetching the push/pull registries from the box config

- shell/ci/release/docker-stitch.sh
- shell/circleci/setup.sh
- shell/lib/docker.sh
- shell/lib/docker_test.bats
This should allow someone to set `BOX_DOCKER_PUSH_IMAGE_REGISTRIES` in the CI environment variables, to test a particular service to push to custom registries.
Also fixes a bug where `docker.sh` didn't include `box.sh` explicitly, even though functions from that library were used.
[DT-4462]
[DT-4462]: https://outreach-io.atlassian.net/browse/DT-4462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: be consistent about determining push registries

- shell/yq.sh
- versions.yaml
This should make running `yq.sh` when `yq` isn't installed much faster and not dependent on `gobin` / `go` installed correctly.
Also, update the `gobin` version of `gojq`.
> fix(yq): use local gojq if installed

- shell/lib/asdf.sh
When running `asdf` initialization within a Docker container, ignore the `~/.asdf` folder as it will install unnecessary runtimes.
[DT-4507]
[DT-4507]: https://outreach-io.atlassian.net/browse/DT-4507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(asdf): when finding .tool-versions, ignore .asdf within containers

- orbs/shared/executors/testbed-docker-aws.yml
- orbs/shared/jobs/test.yaml
Apparently you can't have an executor that works with both AWS and some other auth, practically speaking. If you try to use an executor with a docker image not in AWS, but `aws_auth` is set, it will fail trying to parse the AWS region from the ECR URL.
[DT-4462]
[DT-4462]: https://outreach-io.atlassian.net/browse/DT-4462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(orb): add AWS version of testbed-docker executor

- orbs/shared/jobs/merge.yaml
Replace `bootstrap/ci` with `bootstrap/ci-slim`
> fix(orb): replace reference to unused image

- scripts/devbase.sh
- shell/yq.sh
- templates/scripts/devbase.sh.tpl
- versions.yaml
This avoids a chicken-and-egg problem in CI where it tries to run `gobin` before `go` is even installed, even though `gojq` and/or `yq` is installed locally. Part of this is due to the fact that the Debian/Ubuntu-installed version of `yq` doesn't report its version properly via `yq --version`.
There was also a bunch of variable renames to indicate that they are specific to the JIT-executed `gojq` and not the locally installed `gojq`.
Finally, the bootstrapped `gojq` had its version synced with the version in `versions.yaml`.
> fix(yq): prefer gojq if installed locally

- orbs/shared/commands/setup_docker_auth.yml
- orbs/shared/jobs/docker_amd64.yaml
- orbs/shared/jobs/docker_arm64.yaml
- orbs/shared/jobs/docker_stitch.yaml
- shell/ci/auth/aws-ecr.sh
- shell/ci/auth/gcr.sh
- shell/ci/release/docker-authn.sh
- shell/ci/release/docker-stitch.sh
- shell/ci/release/docker.sh
- shell/circleci/install_gh.sh
- shell/circleci/machine.sh
- shell/circleci/setup.sh
- shell/lib/bootstrap.sh
- shell/lib/docker/authn/aws-ecr.sh
- shell/lib/docker/authn/gcr.sh
* Reduce the amount of setup in the `shared/docker_*` jobs by replacing `setup_environment` with the bare minimum setup required to authenticate to Docker image registries (via the `shared/docker_auth` command). This saves about 1m30s in every (successful) CircleCI run. A side effect of this was to avoid running the `mage version` command, which requires installing Go.
* Use both the push and pull registry values from either the environment or the box config to determine which registries need to be authenticated.
* Make sure that the ECR repository exists before pushing to it.
[DT-4462]
[DT-4462]: https://outreach-io.atlassian.net/browse/DT-4462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(docker): slim down jobs, ensure auth happens

- orbs/shared/jobs/docker_amd64.yaml
- orbs/shared/jobs/docker_arm64.yaml
- shell/ci/release/docker-authn.sh
This fixes the case where building Docker images can't access Go modules in private repositories.
[DT-4558]
[DT-4558]: https://outreach-io.atlassian.net/browse/DT-4558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(docker): ensure ssh is set up for private git repos

- .tool-versions
> fix: upgrade golangci-lint to 1.62.2

- shell/lib/bootstrap.sh
- shell/lib/bootstrap_test.bats
Porting over the Magefile version of `get_app_version` did not work as intended, and it's unclear why.
* Removed `--always` from `git describe` so that a repo without any tags actually uses the fallback.
* Updated the value passed to `--match` to be a glob instead of a regex, per the docs.
* Minor change: prefix fallback version with `v` for consistency
Also adds tests to show what it's supposed to do.
[DT-4561]
`--always` documentation from `git describe --help`:
```
--always
Show uniquely abbreviated commit object as fallback.
```
[DT-4561]: https://outreach-io.atlassian.net/browse/DT-4561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(get_app_version): work as intended, add tests

- shell/lib/docker.sh
- shell/lib/docker_test.bats
[DT-4580]
[DT-4580]: https://outreach-io.atlassian.net/browse/DT-4580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(docker): add tags for all push registries to built containers

- orbs/shared/jobs/e2e.yaml
Adding `test_flags` parameter for e2e tests, so we can tweak a bit how the tests run, e.g. running them in serialised manner.
[XX-XX]
> feat: test_flags parameter for e2e

- orbs/shared/jobs/save_cache.yaml
This gives us consistency with the `shared/test` job.
[DT-4466]
[DT-4466]: https://outreach-io.atlassian.net/browse/DT-4466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(orb): allow executor_name to be parameterized for shared/save_cache

- shell/ci/release/docker-authn.sh
- shell/circleci/install_gh.sh
- shell/gobin.sh
- shell/lib/github.sh
- shell/lib/mise.sh
- versions.yaml
This should avoid some weirdness with using `gobin` for `gojq`.
[DT-4593]
[DT-4593]: https://outreach-io.atlassian.net/browse/DT-4593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: use mise to install gh/gojq for docker jobs

- shell/ci/env/asdf.sh
Prior to this PR, default packages were only configured if `.asdf` didn't exist in the first place, which is not a fair assumption when language versions are changing.
[DT-4598]
[DT-4598]: https://outreach-io.atlassian.net/browse/DT-4598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(asdf): always set up default packages for when new language versions are installed

- versions.yaml
[DT-4599]
[DT-4599]: https://outreach-io.atlassian.net/browse/DT-4599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: upgrade delve to a version with Go 1.23 support

- orbs/shared/commands/setup_docker_auth.yml
- orbs/shared/jobs/docker_amd64.yaml
- orbs/shared/jobs/docker_arm64.yaml
Apparently certain repos with git submodules require that ssh keys be used in the `docker_stitch` job, so just add it to the `setup_docker_auth` command and deduplicate the step.
[DT-4610]
[DT-4610]: https://outreach-io.atlassian.net/browse/DT-4610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(orb): all docker auth commands require ssh keys

- orbs/shared/jobs/merge.yaml
- orbs/shared/jobs/save_cache.yaml
- orbs/shared/jobs/test.yaml
- root/Makefile
- shell/build-jsonnet.sh
* Replaces the hardcoded default in `shell/build-jsonnet.sh` with fetching the box value
* Removes the default image value from a bunch of jobs. (All Outreach CircleCI configs should be specifying the docker image URL via Stencil anyway.)
* Removes an unused `Makefile` variable
* Adds an executor config to a job which I'm pretty sure is unused, but I don't want to remove just yet. I'm changing it because I don't want others to think it *needs* to be changed just because it had a hardcoded reference in it.
[DT-4466]
Replaces / closes #879.
The remaining references are either for GCR authentication, or a default in the `shared/testbed-docker` executor which is fine to keep as a default. If they need to use some non-AWS registry, that's the executor to use and they can just specify …
> fix: remove most of the remaining hardcoded GCR references

- .circleci/config.yml
Follow-up from https://github.com/getoutreach/devbase/pull/885#discussion_r2025822408
[DT-4711]
[DT-4711]: https://outreach-io.atlassian.net/browse/DT-4711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: use shared orb version 2.31.0-rc.1

- orbs/shared/jobs/e2e.yaml
The default devenv snapshot currently takes about 14 minutes to restore (without any output). Double the default from 10m to 20m to have some breathing room, before we have to increase it again.
> fix(orb): double the default no output timeout for E2E jobs to 20m

- orbs/shared/jobs/e2e.yaml
[DT-4759]
[DT-4759]: https://outreach-io.atlassian.net/browse/DT-4759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(orb): add restore and provision timeout parameters to E2E job

- shell/lib/mise.sh
This prevented `shell/circleci/machine.sh` from being executed in `Dockerfile`s.
> fix(mise): only add to BASH_ENV if it exists

- shell/ci/env/asdf.sh
- shell/circleci/machine.sh
- shell/lib/mise.sh
- shell/yq.sh
- templates/scripts/devbase.sh.tpl
- versions.yaml
When running `circleci/machine.sh` in a `Dockerfile`, make sure that other devbase scripts that are called can find `mise`, `gojq` and/or `yq`, regardless of how they're installed.
Also, upgrade `gojq` to the latest version.
The `ci/env/asdf.sh` change is to have CI break if it can't find the protoc versions from `versions.yaml` for whatever reason.
> fix(yq): add support for finding gojq/yq via mise

- shell/ci/auth/github.sh
This allows repos to use this authentication method without needing Go installed.
[DT-4638]
[DT-4638]: https://outreach-io.atlassian.net/browse/DT-4638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ci): use ghaccesstoken via mise instead of gobin

- e2e/e2e.go
- e2e/localizer.go
- shell/ci/testing/delibird.sh
- shell/ci/testing/setup-devenv.sh
Adds a function to find `devenv` in the E2E runner, and makes sure that the `mise` tool shims are available in the E2E shell script.
Also needed to make sure that `vault` was available in both the machine and docker executors.
> fix(e2e): ensure that devenv & other mise-installed tools are runnable

- shell/circleci/setup.sh
GCR only should be authenticated to, if there is a pull/push registry defined using GCR.
> fix(circleci): stop always authenticating to GCR

- shell/circleci/machine.sh
- shell/lib/mise.sh
Allow the `shared/setup_environment` command to run on macOS executors in CircleCI.
Adjusted the mise install script to use a different PGP key server (and made the key ID explicitly longer) as there was a "no route to host" issue on the macOS executor.
> feat(circleci): add support for macOS executors

- shell/build-jsonnet.sh
Currently, we're seeing many services failing their E2E tests in CI because we include a public repo that we maintain called `jsonnet-libs` via a `raw.githubusercontent.com` URL, so jsonnet files imported by `kubecfg` are imported directly over HTTPS. This has predictably led to us getting rate-limited, as our tooling can end up making a ton of requests to that repo specifically, and Github apparently limits requests to `raw.githubusercontent.com` to ~5000/hour/ip address.
https://github.com/github/docs/issues/8031#issuecomment-880564549
To avoid making so many HTTPS request, this modification to the `build-jsonnet.sh` script clones a local copy of the `jsonnet-libs` directory to the local disk, placing that locally cached copy in the `$HOME/.outreach/.cache` folder as that's the blessed …
> fix: cache jsonnet-libs to avoid 429 errors

- shell/build-jsonnet.sh
Fixes a regression in #906 where it was polluting the YAML output of `kubecfg` when it was updating the cache (initial cache creation was fine).
> fix(build-jsonnet): prevent cache updating from polluting output

- shell/catalog-sync.sh
- shell/circleci-orb-sync.sh
- shell/lib/sed.sh
- shell/protoc.sh
- shell/ruby/build.sh
Also extracted `sed_replace` into a couple of reusable functions.
> feat: add script to sync the CircleCI orb version when stencil-circleci isn't used

- shell/ci/auth/vault.sh
- shell/circleci/setup.sh
Reduces the amount of hardcoded items from devbase.
As far as I can tell from a GitHub search, moving the Vault authentication after the pre-setup script and box setup code will not affect any repositories.
> refactor(vault): fetch address from box config

- orbs/shared/jobs/release.yaml
They don't work anymore, but removing them would be a breaking change.
> fix(orb): deprecate docker_* params in release job via docs

- shell/ci/env/mise.sh
- shell/circleci/setup.sh
This is part one of many parts of the `asdf` migration - an opt-in environment variable (already used in `shell/lib/mise.sh`) to use `mise` instead of `asdf` to manage `.tool-versions`. It only works on simple Stenciled repos (that is, only the top-level `.tool-versions`).
[DT-4793]
[DT-4793]: https://outreach-io.atlassian.net/browse/DT-4793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: manage language versions with mise instead of asdf if environment variable set

- shell/linters/prettier.sh
Even if we migrate `prettier` to `mise`, we'll still need `semantic-release` to be in `package.json`. So, check that prettier doesn't exist in `package.json` before checking via `mise`.
[DT-4799]
[DT-4799]: https://outreach-io.atlassian.net/browse/DT-4799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: find prettier via mise even if package.json exists

- shell/linters/prettier.sh
This solution makes it so that when restenciling so that `prettier` is moved from `package.json` into `mise.toml`, it finds prettier correctly, otherwise the `make fmt` during restenciling fails with not being able to find `node_modules/.bin/prettier`.
[DT-4797]
[DT-4797]: https://outreach-io.atlassian.net/browse/DT-4797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: locate prettier at runtime instead of at script load time

- shell/ci/env/mise.sh
- shell/circleci/setup.sh
`mise install` needs to be run in the repo so that `prettier` can be run correctly.
[DT-4813]
[DT-4813]: https://outreach-io.atlassian.net/browse/DT-4813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: always run mise install

- .circleci/config.yml
- Makefile
- shell/catalog-sync.sh
- shell/circleci-orb-sync.sh
- shell/lib/bootstrap.sh
Allow the scripts to be run even if the service doesn't need either of them run. This is in preparation for `mise`-based post-stencil tasks.
This also moves the `devbase`-specific post-stencil orb version sync code into the CircleCI orb sync code, which removes the `perl` dependency when restenciling.
[DT-4791]
[DT-4791]: https://outreach-io.atlassian.net/browse/DT-4791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: clean up post-stencil scripts

- CONTRIBUTING.md
- scripts/unstable-release.include.sh
Missed some references to the old `make` orb tasks when doing the initial conversion.
> chore(orb): update dev publish references

- shell/lib/bootstrap.sh
- shell/lib/bootstrap_test.bats
Also, add tests for some of the newer functions in `shell/lib/bootstrap.sh` to prevent this issue from happening for those.
> fix(bootstrap): select modules from stencil.lock correctly

- .mise/tasks/stencil/_default
- .mise/tasks/stencil/post/_default
- .mise/tasks/stencil/post/catalog-sync
- .mise/tasks/stencil/post/circleci-orb-sync
- .mise/tasks/stencil/upgrade
- root/Makefile
- shell/catalog-sync.sh
- shell/circleci-orb-sync.sh
- shell/deprecated-task.sh
- shell/lib/github.sh
* Moves the `stencil` and `post-stencil` tasks from `make` to `mise`, with a deprecation warning / delay for the old tasks
* Moves the catalog sync and CircleCI orb sync scripts to become `mise` tasks, with a deprecation warning / delay for the old script locations
[DT-4791]
[DT-4791]: https://outreach-io.atlassian.net/browse/DT-4791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: migrate stencil-related tasks to mise

- shell/lib/mise.sh
This is largely for debugging in the event that there's an issue with using `mise`.
[DT-4850]
We're only printing versions if `mise` needs to be installed, because if it doesn't need to be installed, it's usually in a Docker container that can be queried. If we want to change that in the future, that's fine.
[DT-4850]: https://outreach-io.atlassian.net/browse/DT-4850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ci): print mise version after installing

- .mise/tasks/orb/build
- scripts/test.include.sh
First it was a nested quotes problem. Not sure why this didn't show up earlier. Then it appears to be a chicken-and-egg problem with the declared env. The amount of effort isn't worth declaring `sources` for the task.
> fix(tasks): remove sources for orb:build

- orbs/shared/executors/oss-docker.yml
- orbs/shared/jobs/pre-release.yaml
- orbs/shared/jobs/test.yaml
- shell/ci/release/dryrun.sh
- shell/circleci/setup.sh
* Disables service authentication when a forked PR is detected, since no secrets are available with forked PRs
* Adds an OSS Docker executor, defaulting to a public GHCR image
* Allow the `test` and `pre-release` orb jobs to use the new executor
[DT-4869]
A follow-up PR will be needed to enable it for this repo, once the associated `stencil-circleci` PR is merged and in a release candidate.
[DT-4869]: https://outreach-io.atlassian.net/browse/DT-4869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: support forked PRs for OSS repositories

- shell/ci/auth/github_packages.sh
- shell/ci/release/docker-authn.sh
- shell/lib/docker/authn/ghcr.sh
Needed for publishing containers to GHCR. Previously we only had support for GHCR authn if the full authn flow was followed, there are cases where we want to call Docker authentication separately (the same use case for AWS ECR and GCR).
[DT-4870]
[DT-4870]: https://outreach-io.atlassian.net/browse/DT-4870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(authn): modular support for GHCR auth

- shell/devspace_start.sh
Otherwise, `devspace start` hangs trying to ask the user whether the repo's `mise` config is trusted (and the TTY will not allow any interaction).
Also, fixes an uncaught error if `~/.bashrc` doesn't exist.
[DT-4899]
[DT-4899]: https://outreach-io.atlassian.net/browse/DT-4899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(devspace): trust mise config for the repo and its devbase instance
